/*! Copyright 2015 Baidu Inc. All Rights Reserved. */;(function(){var l=void 0,m=!0,q=null,u=!1;function w(f){return function(){return f}}var D=["search!"],la=3,ma="BAIDU_DUP2_replacement",na="http://dup.baidustatic.com/painter/",H=document,I={},oa=0,pa=1,J=2,K=3,L=4,qa=5;function ra(f){var g=sa(f),e=g[0],g=g[1];this.id=f;this.name=g;this.uri=M(g);this.Gd=!g;this.status=oa;e&&g&&(this.Rd=N(P(e+"!"))||{load:function(){}});this.Ua=[]}
var U=window.BAIDU_DUP2_require||function(f,g,e){Q(f,function(){for(var e=[],d=0;d<f.length;d++)e[d]=N(P(f[d]));T(g)&&g.apply(window,e)},e)};
function Q(f,g,e){var i=f.length;if(0===i)g();else for(var d=i,c=0;c<i;c++)(function(c){function b(){if(c.status<J)a();else{for(var b=c.Ua,j=[],d=0;d<b.length;d++){var f=b[d];f&&P(f).status<K&&j.push(f)}0===j.length?a():Q(j,a,e)}}function a(){c&&c.status<K&&(c.status=K);0===--d&&g()}var j=c.Rd;j&&(j.normalize&&(c.name=j.normalize(c.name,M)),j.name2url&&(c.uri=j.name2url(c.name)));c.status<J?j&&T(j.load)?j.load(c.name,U,function(b){V(c.id,[],function(){return b});a()}):ta(c,b,e):b()})(P(f[c]))}
var W={},X={},Y={};function ta(f,g,e){f.status=pa;Y[f.id]?g():X[f.id]?W[f.id].push(g):(X[f.id]=m,W[f.id]=[g],e?(g=f.uri,f=H.createElement("script"),f.charset="utf-8",f.async=m,f.src=g,g=H.getElementsByTagName("head")[0]||H.body,g.insertBefore(f,g.firstChild)):H.write('<script charset="utf-8" src="'+f.uri+'"><\/script>'))}var V=window.BAIDU_DUP2_define||function(f,g,e){var i=P(f);i.status<J&&(i.Ua=g,i.factory=e,i.status=i.Gd?K:J);if(X[f]){delete X[f];Y[f]=m;g=W[f];for(delete W[f];f=g.shift();)f()}};
function N(f){if(!f)return q;if(f.status>=L)return f.oc;if(f.status<K&&f.oc===l)return q;f.status=L;for(var g=[],e=0;e<f.Ua.length;e++)g[e]=N(P(f.Ua[e]));var i=e=f.factory;T(e)&&(i=e.apply(window,g));f.status=qa;return f.oc=i}function M(f){return/^https?:\/\//.test(f)?f:na+f+".js"}function P(f){return I[f]||(I[f]=new ra(f))}function sa(f){var g,e=f?f.indexOf("!"):-1;-1<e&&(g=f.slice(0,e),f=f.slice(e+1,f.length));return[g,f]}
function T(f){return"[object Function]"===Object.prototype.toString.call(f)}
V("util/lang",[],function(){function f(e){for(var f={},d="Array Boolean Date Error Function Number RegExp String".split(" "),c=0,k=d.length;c<k;c++)f["[object "+d[c]+"]"]=d[c].toLowerCase();return e==q?"null":f[Object.prototype.toString.call(e)]||"object"}var g=Object.prototype.hasOwnProperty;return{Xa:g,m:f,getAttribute:function(e,f){for(var d=e,c=f.split(".");c.length;){if(d===l||d===q)return;d=d[c.shift()]}return d},Cc:function(e){if("object"!==f(e))return"";var i=[],d;for(d in e)g.call(e,d)&&
i.push(d+"="+encodeURIComponent(e[d]));return i.join("&")},oa:function(e){var i=[];switch(f(e)){case "object":i=Array.prototype.slice.call(e);break;case "array":i=e;break;case "number":case "string":i.push(e)}return i},unique:function(e){for(var f=[],d={},c=e.length,k=0;k<c;k++){var b=e[k];d[b]||(f[f.length]=b,d[b]=m)}return f},removeItem:function(e,f){for(var d=[].slice.call(e),c=d.length-1;0<=c;c--)d[c]===f&&d.splice(c,1);return d},zc:function(){}}});
V("util/browser",["util/lang"],function(f){var g={},e=navigator.userAgent,i=window.RegExp;/msie (\d+\.\d)/i.test(e)&&(g.d=document.documentMode||+i.$1);/opera\/(\d+\.\d)/i.test(e)&&(g.opera=+i.$1);/firefox\/(\d+\.\d)/i.test(e)&&(g.hd=+i.$1);/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(e)&&!/chrome/i.test(e)&&(g.$d=+(i.$1||i.$2));if(/chrome\/(\d+\.\d)/i.test(e)){g.jc=+i.$1;var d;try{d="scoped"in document.createElement("style")}catch(c){d=u}d&&(g.Xd=m)}try{/(\d+\.\d)/.test(f.getAttribute(window,
"external.max_version"))&&(g.Kd=+i.$1)}catch(k){}f="Android iPad iPhone Linux Macintosh Windows".split(" ");i="";for(d=0;d<f.length&&!(i=f[d],e.match(RegExp(i.toLowerCase(),"i")));d++);g.platform=i;return g});
V("util/dom",["util/lang"],function(f){function g(c){try{if(c&&"object"===typeof c&&c.document&&"setInterval"in c)return m}catch(d){}return u}function e(c,d){d=2===arguments.length?d:c.parent;return c!=d||!g(c)}function i(c,d){for(var d=2===arguments.length?d:c.parent,b=0;10>b++&&e(c,d);){var a;try{a=!!c.parent.location.toString()}catch(j){a=u}if(!a)return m;c=c.parent}return 10<=b}function d(c){return 9===c.nodeType?c:c.ownerDocument||c.document}return{c:function(c,d){return"string"===f.m(c)&&0<
c.length?(d||window).document.getElementById(c):c.nodeName&&(1===c.nodeType||9===c.nodeType)?c:q},$a:g,G:e,S:i,Ha:d,Y:function(c){c=d(c);return c.parentWindow||c.defaultView||q},ha:function(c){c=g(c)?c.document:d(c);return"CSS1Compat"===c.compatMode?c.documentElement:c.body},Eb:function(c,d){1===arguments.length&&"number"===f.m(arguments[0])&&(d=arguments[0],c=l);for(var d=d||10,b=window,a=0;a++<d&&e(b)&&!i(b)&&(!c||!c(b));)b=b.parent;return b}}});
V("util/style",["util/lang","util/dom","util/browser"],function(f,g,e){function i(b,a){if(!b)return"";var j="",j=-1<a.indexOf("-")?a.replace(/[-][^-]{1}/g,function(a){return a.charAt(1).toUpperCase()}):a.replace(/[A-Z]{1}/g,function(a){return"-"+a.charAt(0).toLowerCase()}),h=g.Y(b);if(h&&h.getComputedStyle){if(h=h.getComputedStyle(b,q))return h.getPropertyValue(a)||h.getPropertyValue(j)}else if(b.currentStyle)return h=b.currentStyle,h[a]||h[j];return""}function d(b){var a={top:0,left:0};if(b===g.ha(b))return a;
var j=g.Ha(b),h=j.body,j=j.documentElement;b.getBoundingClientRect&&(b=b.getBoundingClientRect(),a.left=Math.floor(b.left)+Math.max(j.scrollLeft,h.scrollLeft),a.top=Math.floor(b.top)+Math.max(j.scrollTop,h.scrollTop),a.left-=j.clientLeft,a.top-=j.clientTop,b=i(h,"borderLeftWidth"),h=i(h,"borderTopWidth"),b=parseInt(b,10),h=parseInt(h,10),a.left-=isNaN(b)?2:b,a.top-=isNaN(h)?2:h);return a}function c(b,a){var j=i(b,"margin"+a).toString().toLowerCase().replace("px","").replace("auto","0");return parseInt(j,
10)||0}function k(b){for(var a=g.Y(b),j=100;b&&b.tagName;){var h=100;if(e.d){if(5<e.d)try{h=parseInt(f.getAttribute(b,"filters.alpha.opacity"),10)||100}catch(c){}j=j>h?h:j}else{try{h=100*(a.getComputedStyle(b,q).opacity||1)}catch(d){}j*=h/100}b=b.parentNode}return 0===j?0:j||100}return{s:i,ea:d,X:function(b){var a=g.c(b);if(!a)return u;b=d(a);a=g.Y(a);if(!a)return b;for(var j=0;a!==a.parent&&10>j++&&!g.S(a)&&a.frameElement;){var h=d(a.frameElement);b.left+=h.left;b.top+=h.top;a=a.parent}return b},
ze:c,va:function(b,a){var j=g.c(b),h=j.offsetWidth;a&&(h+=c(j,"Left")+c(j,"Right"));return h},ua:function(b,a){var j=g.c(b),h=j.offsetHeight;a&&(h+=c(j,"Top")+c(j,"Bottom"));return h},Fb:k,sc:function(b){for(var a=g.c(b),b=g.Y(a),a=k(a),j=0;10>j++&&g.G(b)&&!g.S(b);){var h=b.frameElement?k(b.frameElement):100,a=a*(h/100);b=b.parent}return a},Ib:function(b){try{var a=g.ha(b||window).scrollWidth;if(a||0===a)return a}catch(j){}return-1},Hb:function(b){try{var a=g.ha(b||window).scrollHeight;if(a||0===
a)return a}catch(j){}return-1},o:function(b){try{var a=g.ha(b||window).clientWidth;if(a||0===a)return a}catch(j){}return-1},j:function(b){try{var a=g.ha(b||window).clientHeight;if(a||0===a)return a}catch(j){}return-1},F:function(b){var a=g.ha(b);return b.pageYOffset||a.scrollTop},Ia:function(b){var a=g.ha(b);return b.pageXOffset||a.scrollLeft}}});
V("util/url",["util/dom"],function(f){return{tc:function(f,e,i){f=f.match(RegExp("(\\?|&|#)"+e+"=([^&#]*)(&|#)?"));e="";f&&(e=f[2]);i&&(e=decodeURIComponent(e));return e},Jb:function(g){var g=f.Eb(g),e="";f.G(g)&&(e=g.document.referrer);return e=e||g.location.href}}});
V("util/event",["util/dom"],function(f){return{bind:function(g,e,i){if(g=f.$a(g)?g:f.c(g))if(g.addEventListener)g.addEventListener(e,i,u);else if(g.attachEvent)g.attachEvent("on"+e,i);else{var d=g["on"+e];g["on"+e]=function(){d&&d.apply(this,arguments);i.apply(this,arguments)}}return g}}});
V("util/cookie",["util/lang"],function(f){return{get:function(f,e){var i=RegExp("(^| )"+f+"=([^;]*)(;|$)").exec(document.cookie);return i?e?decodeURIComponent(i[2]):i[2]:""},set:function(g,e,i,d){var c=i.expires;"number"===f.m(c)&&(c=new Date,c.setTime(+c+i.expires));document.cookie=g+"="+(d?encodeURIComponent(e):e)+(i.path?"; path="+i.path:"")+(c?"; expires="+c.toGMTString():"")+(i.domain?"; domain="+i.domain:"")}}});
V("util/data",["util/lang","util/dom"],function(f,g){function e(a,j,h){var h=h?b:c,d;if("string"===f.m(a)){for(a=a.split(".");a.length;)d=a.shift(),h[d]=a.length?h[d]!==l?h[d]:{}:j,h=h[d];d=j}return d}function i(a,j){var h=j?b:c,d;"string"===f.m(a)&&(d=f.getAttribute(h,a));return d}function d(a,b,h){if(!a||!b)return u;var c=i(a)||{};switch(h){case "+1":h=c[b]||0;c[b]=++h;break;default:c[b]=parseInt(h,10)}e(a,c);return c[b]}var c={},k=g.Eb(),b=k.BAIDU_DUP2_info||(k.BAIDU_DUP2_info={});return{qa:function(a,
b){var c=window;return c[a]?c[a]:c[a]=b},ta:function(a){var b=window,c=b[a];b[a]=l;return c},$:e,C:i,Bc:function(a,j){var h=j?b:c;switch(f.m(a)){case "string":for(var d=a.split(".");d.length;){var e=d.shift();if(d.length&&h[e]!==l)h=h[e];else return delete h[e],m}}return u},hc:function(a,b){return d(a,b,"+1")},Je:function(a,b,c){return d(a,b,c)},count:d,nd:function(a,b){return!a||!b?u:(i(a)||{})[b]||0},Wd:function(a,b){if(!a||!b)return u;var c=i("pageConfig")||{};c[a]=b;e("pageConfig",c);return m},
md:function(a){return!a?u:(i("pageConfig")||{})[a]}}});
V("util/storage",[],function(){function f(d,c,f){if(e)try{e.setItem(d,f?encodeURIComponent(c):c)}catch(b){}}function g(d,c){if(e){var f=e.getItem(d);return c&&f?decodeURIComponent(f):f}return q}var e;try{e=window.localStorage}catch(i){}return{Tc:function(){var d=u;try{e.removeItem("BAIDU_DUP_storage_available"),f("BAIDU_DUP_storage_available","1"),g("BAIDU_DUP_storage_available")&&(d=m),e.removeItem("BAIDU_DUP_storage_available")}catch(c){}return d},setItem:f,getItem:g,Oc:function(d,c,k){if(e){c=
k?encodeURIComponent(c):c;k=g(d)||"";try{f(d,k+((k&&"|")+c))}catch(b){}}},Hc:function(d,c,k){if(e)if(c=k?encodeURIComponent(c):c,k=g(d)||"",k=k.replace(RegExp(c+"\\|?","g"),"").replace(/\|$/,""))try{f(d,k)}catch(b){}else e.removeItem(d)}}});
V("util/log",["util/lang","util/event","util/storage"],function(f,g,e){function i(c,e){var b=new Image,a="BAIDU_DUP_log_"+Math.floor(2147483648*Math.random()).toString(36);window[a]=b;b.onload=b.onerror=b.onabort=function(){b.onload=b.onerror=b.onabort=q;b=window[a]=q;e&&e(d,c,m)};b.src=c}var d="BAIDU_DUP_log_storage";return{Ee:i,Ke:function(){var c=e.getItem(d);if(c)for(var c=c.split("|"),f=0,b=c.length;f<b;f++)i(decodeURIComponent(c[f]),e.Hc)},hb:function(c){var c="object"===f.m(c)?c:{},k=c.url||
"http://cbjslog.baidu.com/log",b=c.option||"now",c=f.Cc(c.data||{}),k=k+((0<=k.indexOf("?")?"&":"?")+c+(c?"&":"")+"rdm="+ +new Date);switch(b){case "now":i(k);break;case "block":break;default:e.Oc(d,k,m),g.bind(window,"unload",function(){i(k,e.Hc)})}}}});V("util","util/lang,util/dom,util/style,util/url,util/event,util/cookie,util/data,util/storage,util/log,util/browser".split(","),function(f,g,e,i,d,c,k,b,a,j){return{lang:f,p:g,style:e,url:i,event:d,cookie:c,data:k,Pe:b,log:a,e:j}});
V("biz",["util","slot"],function(f,g){function e(c,b){var a=/^[0-9a-zA-Z]+$/;return!c||!a.test(c)||!b?[]:b="array"===f.lang.m(b)?b:Array.prototype.slice.call(arguments,1)}function i(e,b,a){if(!b||!b.length)return u;var a=a||{cc:u,yc:u,Ac:u},j=a.yc?f.data.C(d):{},h=a.cc?c:d,j=a.Ac?{}:f.data.C(h)||j,a={},p;for(p in j)f.lang.Xa.call(j,p)&&(a[p]="array"===f.lang.m(j[p])?j[p].slice():j[p]);var j=a[e]||[],t=b.length;for(p=0;p<t;p++){var i=b[p];"string"===typeof i&&(i=encodeURIComponent(i),100>=i.length&&
(j[j.length]=i))}if(!j.length)return u;a[e]=f.lang.unique(j);f.data.$(h,a);return m}var d="bizOrientations",c="bizUrgentOrientations";return{ic:function(c,b){var a=e.apply(this,arguments);return i(c,a)},Pc:function(c,b){var a=e.apply(this,arguments);return i(c,a,{cc:m,yc:m})},ce:function(c,b){var a=e.apply(this,arguments);return i(c,a,{cc:m,Ac:m})},wd:function(e){var e=Math.max(0,Math.min(e||500,500)),b=[],a=f.data.C(c)||f.data.C(d)||{};if("object"===f.lang.m(a))for(var j in a)f.lang.Xa.call(a,j)&&
(b[b.length]=j+"="+a[j].join(","));f.data.$(c,l);b.sort(function(a,b){return a.length-b.length});a="";j=b.length;for(var h=0;h<j&&!(a.length+b[h].length>=e);h++)a+=(h?"&":"")+b[h];return a},Qc:function(c,b){g.ee(c);g.Rc(b)}}});
V("preview",["biz","util"],function(f,g){function e(){function f(a){var b=g.url.tc;return b(d,"baidu_clb_preview_"+a)||b(d,"baidu_dup_preview_"+a)}var d=g.url.Jb(),c=f("sid"),k=f("mid"),b=f("vc"),a=+f("ts"),j=q;3E4>=+new Date-a&&(j={Ec:c,Ld:k,le:b});e=function(){return j};return j}return{yd:function(f){var d=[],c=e();c&&f==c.Ec&&(d.push("mid="+c.Ld),d.push("sid="+c.le));return d.join("&")},C:function(){return e()},Za:function(e){var d=u;e?/cpro_template=/gi.test(e)&&(g.data.$("#unionPreviewSwitch",
m),d=m):d=!!g.data.C("#unionPreviewSwitch");return d},zd:function(){var e=g.data.C("#unionPreviewData");return e?"prev="+encodeURIComponent(e)+"&pt=union":""},fe:function(e){g.data.$("#unionPreviewData",e)},ve:function(){g.data.Bc("#unionPreviewSwitch");g.data.Bc("#unionPreviewData")}}});
V("slot",["util"],function(f){function g(){for(var b={response:{},holder:"",stack:[],errors:[],status:{}},c=a.length-1;0<=c;c--)b.status[a[c]]=0;return b}function e(a,b){var c=u;"fillAsync"===b&&(c=m);p[a]&&-1!==p[a].stack.join(" ").toLowerCase().indexOf("async")&&(c=m);return c}function i(a,b){if(!a)return"";var c=n+a;b&&(c+="_"+b);return c}function d(a,b,c){if(!a||!b)return u;c===l&&(c=+new Date);if(p[a]){p[a].status[b]=c;if("finish"===b){var b={},c=u,j;for(j in s)if(j&&s.hasOwnProperty(j)&&s[j]&&
0===(""+a).indexOf(""+j)&&p[a].response){var c=p[a].response.data,d=c._h||c.sh||c.height||0;b[a]=0===(c._w||c.sw||c.width||0)||0===d?u:m;c=m}c&&t.apply(window,[b])}return m}return u}function c(a,b){k(a,"errors",b)}function k(a,b,c){a&&b&&c&&(a=p[a])&&"array"===f.lang.m(a[b])&&a[b].push(c)}function b(a){return!a?p:p[a]||u}var a="add,create,request,response,render,finish".split(","),j=[],h={},p={},t,s={},n="BAIDU_DUP_wrapper_";return{add:function(){var a={ids:[],preloadIds:[]},c=f.lang.oa(arguments);
if(!c.length)return a;for(var c=c.join(",").split(","),e=[],k=[],t=c.length,i=0;i<t;i++){var s=c[i];if(h.hasOwnProperty(s)){var n=s+"_"+h[s],v=b(n).stack||[];if("preload"===v[v.length-1]){a.preloadIds.push(n);continue}h[s]+=1}else h[s]=0;s=s+"_"+h[s];p[s]=new g;d(s,"add");k.push(s);e.push(s)}j=j.concat(k);a.ids=e;return a},create:function(a,b,j){if(!a||!b)return u;var h=i(a),k=m;if(f.p.c(h))return p[a].holder=h,k;if(e(a,b)){j=j||"";p[a].holder=j;j=f.p.c(j);try{j&&(j.innerHTML='<div id="'+h+'"></div>',
p[a].holder=h)}catch(t){c(a,"Failed to insert wrapper"),k=u}}else if(document.write('<div id="'+h+'"></div>'),!f.p.c(h))try{var g=document.getElementsByTagName("script"),s=g[g.length-1];if(s){var n=s.parentNode;if(n){var E=document.createElement("div");E.id=i(a,"b");n.insertBefore(E,s)}}}catch(C){c(a,"Failed to create backup wrapper")}d(a,"create");return k},cd:e,qd:function(a){return e(a)?"async":"sync"},rc:function(a){return!a?"":(a=f.p.c(p[a].holder)||f.p.c(i(a))||f.p.c(i(a,"b")))&&a.id||""},Wa:b,
Wb:function(a,b){if(!a||!b)return u;return p[a]?(p[a].response=b,d(a,"response"),m):u},za:d,ma:c,sb:function(a,b){k(a,"stack",b)},Db:function(a){a=f.lang.oa(a);if(!a.length)return u;var b=[],c={},h;for(h=0;h<j.length;h++)c[j[h]]=h+1;for(h=0;h<a.length;h++){var d=c[""+a[h]];d===l&&(d=0);b.push(d)}return b},ee:function(a){t=a},Rc:function(a){s[a]=m},X:function(a){a=f.lang.oa(a);if(!a.length)return["-1x-1"];for(var b=[],j=0;j<a.length;j++){var h=a[j],d;try{var e=f.p.c(i(h))||f.p.c(i(h,"b"));if(e){var k=
f.style.X(e);k&&(d=[k.top,k.left])}}catch(p){c(h,"Unable to get ps")}d=d?d:[-1,-1];b.push(d.join("x"))}return b}}});V("api",["slot","util"],function(f,g){return{getDai:f.Db,getSlots:f.Wa,getFillType:f.qd,getFillWrapperId:f.rc,setStatus:f.za,addErrorItem:f.ma,addStackItem:f.sb,bind:g.event.bind,getType:g.lang.m,sendLog:g.log.hb,putInfo:g.data.$,getInfo:g.data.C,defineOnce:g.data.qa,addCount:g.data.hc,getCount:g.data.nd,getConfig:g.data.md}});
V("param",["slot","preview","biz","util"],function(f,g,e,i){function d(a,b){for(var b=b||0,c=[],j=0,h=a.length;j<h;j++)c.push(a[j].split("_")[b]);return c.join(",")}function c(a){a=a||window.document.domain;0===a.indexOf("www.")&&(a=a.substr(4));"."===a.charAt(a.length-1)&&(a=a.substring(0,a.length-1));var b=a.match(RegExp("([a-z0-9][a-z0-9\\-]*?\\.(?:com|cn|net|org|gov|info|la|cc|co|jp|us|hk|tv|me|biz|in|be|io|tk|cm|li|ru|ws|hn|fm|tw|ma|in|vn|name|mx|gd|im)(?:\\.(?:cn|jp|tw|ru|th))?)$","i"));return b?
b[0]:a}var k=window,b=k.document,a=k.screen,j=k.navigator,h=+new Date,p=[{key:"di",value:function(a){return d(a.id)}},{key:"dcb",value:w("BAIDU_DUP2_define")},{key:"dtm",value:w("BAIDU_DUP2_SETJSONADSLOT")},{key:"dbv",value:function(){var a=i.e;return a.Xd?"1":a.jc?"2":"0"}},{key:"dci",value:function(a){for(var b="-1",c={fill:"0",fillOnePiece:"1",fillAsync:"2",preload:"3"},j=0;j<a.id.length;j++){var h=f.Wa(a.id[j]);if(h){var h=h.stack,d=h.length;if(1<=d){b=c[h[d-1]];break}}}return b}},{key:"dri",
value:function(a){return d(a.id,1)}},{key:"dis",value:function(){var a=0;i.p.G(k)&&(a+=1);i.p.S(k,k.top)&&(a+=2);var b=i.style.o(),c=i.style.j();if(40>b||10>c)a+=4;return a}},{key:"dai",value:function(a){return f.Db(a.id).join(",")}},{key:"dds",value:function(){var a=i.data.C("dds");return i.lang.Cc(a)}},{key:"drs",value:function(){var a={uninitialized:0,loading:1,loaded:2,interactive:3,complete:4};try{return a[b.readyState]}catch(c){return-1}}},{key:"dvi",value:w("1421115315")},{key:"ltu",Fa:m,value:function(){var a=
i.url.Jb(function(a){var b=i.style.o(a),a=i.style.j(a);return 400<b&&120<a?m:u});0<a.indexOf("cpro_prev")&&(a=a.slice(0,a.indexOf("?")));return a}},{key:"liu",Fa:m,value:function(){return i.p.G(k)?b.URL:""}},{key:"ltr",Fa:m,value:function(){var a=i.p.Eb(),b="";try{b=a.opener?a.opener.document.location.href:""}catch(c){}return b||a.document.referrer}},{key:"lcr",Fa:m,value:function(){var a=b.referrer,j=a.replace(/^https?:\/\//,""),j=j.split("/")[0],j=j.split(":")[0],j=c(j),h=c(),d=i.cookie.get("BAIDU_DUP_lcr");
if(d&&h===j)return d;return h!==j?(i.cookie.set("BAIDU_DUP_lcr",a,{domain:h}),a):""}},{key:"ps",value:function(a){return f.X(a.id).join(",")}},{key:"psr",value:function(){return[a.width,a.height].join("x")}},{key:"par",value:function(){return[a.availWidth,a.availHeight].join("x")}},{key:"pcs",value:function(){return[i.style.o(),i.style.j()].join("x")}},{key:"pss",value:function(){return[i.style.Ib(),i.style.Hb()].join("x")}},{key:"pis",value:function(){return(i.p.G(k)?[i.style.o(),i.style.j()]:[-1,
-1]).join("x")}},{key:"cfv",value:function(){var a=0;if(j.plugins&&j.mimeTypes.length){var b=j.plugins["Shockwave Flash"];b&&b.description&&(a=b.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")+".0")}else if(k.ActiveXObject&&!k.opera)for(b=10;2<=b;b--)try{var c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+b);c&&(a=c.GetVariable("$version").replace(/WIN/g,"").replace(/,/g,"."))}catch(h){}return parseInt(a,10)}},{key:"ccd",value:function(){return a.colorDepth||0}},{key:"chi",value:function(){return k.history.length||
0}},{key:"cja",value:function(){return j.javaEnabled().toString()}},{key:"cpl",value:function(){return j.plugins.length||0}},{key:"cmi",value:function(){return j.mimeTypes.length||0}},{key:"cce",value:function(){return j.cookieEnabled||0}},{key:"col",value:function(){return(j.language||j.browserLanguage||j.systemLanguage).replace(/[^a-zA-Z0-9\-]/g,"")}},{key:"cec",value:function(){return(b.characterSet?b.characterSet:b.charset)||""}},{key:"cdo",value:function(){var a=window.orientation;a===l&&(a=
-1);return a}},{key:"tsr",value:function(){var a=0,b=+new Date;h&&(a=b-h);return a}},{key:"tlm",value:function(){return Date.parse(b.lastModified)/1E3}},{key:"tcn",value:function(){return Math.round(+new Date/1E3)}},{key:"tpr",value:function(a){var a=a&&a.max_age?a.max_age:24E4,b=(new Date).getTime(),c,j;try{c=!!window.top.location.toString()}catch(h){c=u}j=c?window.top:window;(c=j.BAIDU_DUP2_pageFirstRequestTime)?b-c>=a&&(c=j.BAIDU_DUP2_pageFirstRequestTime=b):c=j.BAIDU_DUP2_pageFirstRequestTime=
b;return c||""}},{key:"_preview",value:function(a){return g.yd(d(a.id))}},{key:"dpt",value:function(){var a="none";g.Za()&&(a="union");return a}},{key:"coa",Fa:m,value:function(a){var b=a.id,b=b[0].split("_")[0],a={},c=u,j=i.data.C("#novaOpenApi");if(j&&b&&j[b]){var c=m,b=j[b],h;for(h in b)h&&b.hasOwnProperty(h)&&"undefined"!==typeof b[h]&&(a[h]=encodeURIComponent(b[h]).toString())}c&&(a.c01=1);h="";for(var d in a)d&&a.hasOwnProperty(d)&&"undefined"!==typeof a[d]&&(h+="&"+d+"="+a[d]);return h=h.slice(1)}},
{key:"_unionpreview",value:function(){return g.zd()}},{key:"baidu_id",value:w("")},{key:"_orientation",value:function(){return e.wd()}}];return{get:function(a,b){for(var c=[],j=0,h=p.length;j<h;j++){var d;try{var e=p[j],f=e.key,k=e.Fa,g=e.value,g="function"===typeof g?g(a):g,g=k?encodeURIComponent(g):g;if(b&&b===f)return g;d=f&&0!==f.indexOf("_")?f+"="+g:g}catch(i){d=encodeURIComponent(i.toString()),d=d.slice(0,100)}d&&c.push(d)}c=c.join("&");return c.slice(0,2048)}}});
V("request",["param","slot","util"],function(f,g,e){V("request!",[],{name2url:function(e){return"http://pos.baidu.com/acom?"+f.get({id:e.split(",")})}});V("batch!",[],{name2url:function(e){return"http://pos.baidu.com/acom?"+f.get({id:e.split(",")})}});return{send:function(f,d,c){if(!f||!d||c===l)return u;var k=[];if("array"!==e.lang.m(f))g.za(f,"request"),k=["request!"+f];else{for(k=0;k<f.length;k++)g.za(f[k],"request");k=1===f.length?["request!"+f[0]]:["batch!"+f.join(",")]}U(k,d,c);return m}}});
V("control",["slot","request","preview","util"],function(f,g,e,i){function d(b,a,c){var h=a.deps,d=a.data,e=f.rc(b);c&&!e?f.ma(b,"HolderNotFound"):h&&(0>h[0].indexOf("clb/")&&f.za(b,"finish"),U(h,function(a){if("object"===i.lang.m(d)){d.id=b;if(a.hasOwnProperty("validate"))try{var c=a.validate(d);c!==m&&i.log.hb({data:{type:c||"ResponseError",errorPainter:h[0],id:b,slotType:d._stype,materialType:d._isMlt,html:!!d._html}})}catch(j){f.ma(b,"validateException")}if(a.hasOwnProperty("render"))try{f.za(b,
"render"),a.render(d,e)}catch(k){f.ma(b,"RenderException")}else f.ma(b,"RenderNotFound")}else f.ma(b,"ResponseFormatError")},c))}function c(b,a,c){if(!b)return u;var c=c||"",h=f.add(b),b=h.ids[0]||h.preloadIds[0];if(!b)return u;var e=f.cd(b,a);f.sb(b,a);f.create(b,a,c);h.ids.length?g.send(b,function(a){f.Wb(b,a);d(b,a,e)},e):h.preloadIds.length&&(a=f.Wa(b).response,d(b,a,e));return m}function k(b){for(var a=0,c=b+"_"+a;0!==f.Db([c])[0];){var h=f.Wa(c);if((h=h&&h.response)&&0===h.deps[0].indexOf("clb/")){var d=
h.data,h=d._isMlt;(0===h&&""!==d._html||h===u&&d._fxp)&&f.za(c,"finish",0)}c=b+"_"+ ++a}if(b!==l&&(b=(a=window.BAIDU_CLB_SLOTS_MAP)&&a[b],b!==l&&(h=b._isMlt,0===h&&""!==b._html||h===u&&b._fxp)))b._done=u}window.BAIDU_CLB_prepareMoveSlot=k;return{fill:function(b){return c(b,"fill")},zb:function(b,a){return c(b,"fillAsync",a)},Sd:function(){function b(a){g.send(a,function(b){if("array"===i.lang.m(b)){if(b&&b.length===a.length)for(var c=0;c<a.length;c++)f.Wb(a[c],b[c])}else"object"===i.lang.m(b)&&b&&
1===a.length&&f.Wb(a[0],b)},u)}var a=i.lang.oa(arguments),a=i.lang.unique(a),c=e.C();if(c)for(var h=0,d=a.length;h<d;h++)a[h]==c.Ec&&(a.splice(h,1),h--);for(a=f.add(a).ids;a.length;){c=a.splice(0,16);for(h=0;h<c.length;h++)f.sb(c[h],"preload");b(c)}},Ud:k}});
V("global",["control","biz","util","preview"],function(f,g,e,i){function d(a){a=a.split(".");return j[a[0]]+a[1]}function c(){var c=a.BAIDU_DUP2;if(!("object"===e.lang.m(c)&&c.push)){if("array"===e.lang.m(c)&&c.length)for(var d=0;d<c.length;d++)k(c[d]);a.BAIDU_DUP2=l;e.data.qa("BAIDU_DUP2",{push:k});e.data.qa("BAIDU_DUP2_proxy",function(a){if(a)return function(){try{return k([a].concat(e.lang.oa(arguments)))}catch(b){0<la--&&e.log.hb({data:{type:"ExecuteException",errorName:a,args:e.lang.oa(arguments).join("|"),
isQuirksMode:"CSS1Compat"!==document.compatMode,documentMode:document.documentMode||"",readyState:document.readyState||"",message:b.message}})}}});for(d in p)d&&e.lang.Xa.call(p,d)&&e.data.qa(d,a.BAIDU_DUP2_proxy(d));b()}}function k(a){if("array"!==e.lang.m(a))return u;var b=a.shift();e.data.hc("apiCount",b);return(b=p[b]||t[b]||u)&&b.apply(q,a)}function b(){function a(b){for(var c=0,d=D.length;c<d;c++)if(0===b.indexOf(D[c]))return m;return u}e.data.qa("BAIDU_DUP2_require",function(b){for(var c=0,
d=b.length;c<d;c++)if(a(b[c]))return;U.apply(q,arguments)});e.data.qa("BAIDU_DUP2_define",function(b,c){for(var d=0,h=c.length;d<h;d++)if(a(c[d]))return;V.apply(q,arguments)})}var a=window,j={clb:"BAIDU_CLB_DUP2_",dan:"BAIDU_DAN_DUP2_",nova:"cpro",dup:"BAIDU_DUP_"},h=[{O:["clb.fillSlot","clb.singleFillSlot","clb.fillSlotWithSize"],P:["fill"],N:f.fill},{O:["clb.fillSlotAsync"],P:["fillAsync"],N:f.zb},{O:["clb.preloadSlots"],P:["preload"],N:f.Sd},{O:["clb.prepareMoveSlot"],P:["prepareMove"],N:f.Ud},
{O:["clb.addOrientation"],P:["addOrientation"],N:g.ic},{O:["clb.addOrientationOnce"],P:["addOrientationOnce"],N:g.Pc},{O:["clb.setOrientationOnce"],P:["setOrientationOnce"],N:g.ce},{O:["clb.setConfig"],P:["putConfig"],N:e.data.Wd},{O:["clb.addSlot","clb.enableAllSlots","clb.SETHTMLSLOT"],P:[],N:e.lang.zc},{O:["dup.addSlotStatusCallback"],P:[],N:g.Qc}],h=function(a){for(var b={},c={},h=0;h<a.length;h++){for(var j=a[h],e=j.O,f=j.P,j=j.N;e.length;)b[d(e.shift())]=j;for(;f.length;)c[f.shift()]=j}return{Nd:b,
Vd:c}}(h),p=h.Nd,t=h.Vd;return{Bd:function(){var a=e.data.ta(d("clb.ORIENTATIONS"));if(a)for(var b in a)Object.prototype.hasOwnProperty.call(a,b)&&g.ic(b,a[b]);e.data.$("#novaOpenApi",e.data.ta("cproStyleApi"));var h=e.data.ta("cproArray");if(h)for(var a=0,j=h.length;a<j;a++)h[a]&&h[a].id&&f.zb(h[a].id,"cpro_"+h[a].id);if(h=e.data.ta("cpro_mobile_slot")){a=0;for(j=h.length;a<j;a++){var k=h[a],p=k.id,t=e.data.C("#novaOpenApi")||{};t[p]||(t[p]={});for(b in k)b&&"id"!==b&&k.hasOwnProperty(b)&&(t[p][b]=
k[b]);e.data.$("#novaOpenApi",t);h[a]&&h[a].id&&f.zb(h[a].id,"cpro_"+h[a].id)}}if(b=e.data.ta("cpro_id"))i.Za(b)&&(i.fe(b),b="u0"),f.fill(b);f.fill(e.data.ta(d("clb.SLOT_ID")));c()}}});V("logService",["util/lang","util/event"],function(f,g){g.bind(window,"load",function(){U(["detect"],f.zc,m)})});
V("fingerprint",["util/storage","util/event","util/browser","util/data","param"],function(f,g,e,i,d){var c=window,k=u;e.d?6<=e.d&&(k=m):f.Tc()&&(k=m);0<=c.location.href.indexOf("wa.kuwo.cn")||(k&&(i.C("isFPLoaded",m)===m?k=u:i.$("isFPLoaded",m,m)),k&&g.bind(c,"load",function(){var b=c.document,a=b.body,j="http://pos.baidu.com/wh/o.htm?ltr="+d.get({},"ltr"),j=j+"&cf=u",h=b.createElement("div");h.id="BAIDU_DUP_fp_wrapper";h.style.position="absolute";h.style.left="-1px";h.style.bottom="-1px";h.style.zIndex=
0;h.style.width=0;h.style.height=0;h.style.overflow="hidden";h.style.visibility="hidden";h.style.display="none";b=b.createElement("iframe");b.id="BAIDU_DUP_fp_iframe";b.src=j;b.style.width=0;b.style.height=0;b.style.visibility="hidden";b.style.display="none";try{h.insertBefore(b,h.firstChild),a&&a.insertBefore(h,a.firstChild)}catch(e){}}))});V("replacement",["util"],function(f){function g(){var e=f.url.Jb(),i=f.url.tc(e,ma,m);g=function(){return i};return i}return{xd:function(){return g()}}});
U(["replacement"],function(f){(f=f.xd())?U([f]):(U(["global"],function(f){f.Bd()}),U(["logService"]),U(["fingerprint"]))});
window.BAIDU_DUP2_define&&window.BAIDU_DUP2_define("detect",["api"],function(f){function g(e){e.url="";e.host=window.location.hostname;e.from="DUP";f.sendLog({data:e,He:"now"})}try{setTimeout(function(){var e=f.getSlots(),d;for(d in e){var c=e[d],k=c.response,b=u;if("object"!==f.getType(k))b=m;else{var b=m,a;for(a in k)if(Object.prototype.hasOwnProperty.call(k,a)){b=u;break}}var j=c.status,c=c.stack;b?g({type:"preload"===c[0]?"preloadFail":"loadFail",id:d}):!j.render&&!j.finish&&g({type:"renderFail",
id:d,error:"preload"===c[0]?"PreloadNotFilled":"NotFilled",empty:!(!k.data||!k.data._html)})}},0)}catch(e){}});
window.BAIDU_DUP2_define&&window.BAIDU_DUP2_define("viewWatch",["util","param"],function(f,g){function e(){var a=+new Date,d=500;r===b&&B&&(d=a-B);B=a;for(var j in t)if(p.call(t,j)){r===c&&(r=k);var e=t[j];e.cb&&(e.Nb+=d);e.bb&&(e.Mb+=d);e.Rb=a-e.timestamp;if(r===b)x&&(e.Va+=a-e.ab);else if(72E5<=e.Rb)i(u);else{var g=e=l,s=l;for(s in t)if(p.call(t,s)){var n=t[s];if(x){var o=f.p.c(n.ne);if(!o)break;try{var $=h.o(y),aa=h.j(y),O=h.X(o);n.top=O.top;n.left=O.left;var ba=h.F(y),ca=h.Ia(y),da=h.va(o),ea=
h.ua(o),fa=O.top-ba+0.35*ea,ga=O.left-ca+0.35*da;n.cb=0<fa&&fa<aa&&0<ga&&ga<$;var ua=da*ea,ha=h.X(o),R=ha.top-ba,S=ha.left-ca,ia=h.va(o),ja=h.ua(o),ka=o=0,o=0>R?Math.max(R+ja,0):Math.min(ja,Math.max(aa-R,0)),ka=0>S?Math.max(S+ia,0):Math.min(ia,Math.max($-S,0));e=ka;g=o;n.bb=g*e>0.5*ua}catch(va){n.cb=u,n.bb=u}}else n.cb=u,n.bb=u}}}}function i(c){clearInterval(n);var h=document.domain.toLowerCase();if(!(-1<h.indexOf("autohome.com.cn")||-1<h.indexOf("sina.com.cn")||-1<h.indexOf("pconline.com.cn")||-1<
h.indexOf("pcauto.com.cn")||-1<h.indexOf("pclady.com.cn")||-1<h.indexOf("pcgames.com.cn")||-1<h.indexOf("pcbaby.com.cn")||-1<h.indexOf("pchouse.com.cn")||-1<h.indexOf("xcar.com.cn")))if(r!==k)r=b;else{r=b;e();var h=u,j;for(j in t)if(j&&t.hasOwnProperty(j)&&t[j]){var g=t[j];"block"===g.Jd&&(h=m);g.total=s;f.log.hb({url:d(g)})}if(c&&h)if(c=+new Date,a.d)for(h=c+200;h>+new Date;);else{j=1E5;for(h=0;h<j;h++);h=+new Date;j=Math.min(200*j/(h-c),1E7);for(h=0;h<j;h++);}}}function d(a){var b=["tu="+a.id,"word="+
g.get(l,"ltu"),"if="+g.get(l,"dis"),"aw="+a.width,"ah="+a.height,"pt="+a.Rb,"it="+a.Nb,"vt="+a.Mb,"csp="+o,"bcl="+a.Yc,"pof="+a.ae,"top="+a.top,"left="+a.left,"total="+a.total];return a.url+(a.pc?a.pc+"&":"")+b.join("&")}var c=1,k=2,b=3,a=f.e,j=f.event.bind,h=f.style,p=f.lang.Xa,t=[],s=0,n=0,r=c,x=m,B=0,o=[1E4<screen.availWidth?0:screen.availWidth,1E4<screen.availHeight?0:screen.availHeight].join(),y=window;f.p.G(window)&&!f.p.S(window)&&(y=window.top);n=setInterval(e,500);(function(){function b(){var a=
+new Date,c;for(c in t)if(p.call(t,c)){var h=t[c];h.Va+=a-h.ab;h.ab=a}x=u}function c(){var a=+new Date,b;for(b in t)p.call(t,b)&&(t[b].ab=a);x=m}a.d?(j(document,"focusin",c),j(document,"focusout",b)):(j(window,"focus",c),j(window,"blur",b))})();j(window,"beforeunload",i);return{register:function(a){var b=+new Date,c=a.id,d=a.wrapperId,j=a.url||"http://eclick.baidu.com/a.js?",e=a.logType||"storage",a=a.extra||"";if(d&&!t[d]){var k=f.p.c(d);if(k){var g=h.X(k);t[d]={id:c,ne:d,url:j,Jd:e,pc:a,timestamp:b,
Nb:0,cb:u,Mb:0,bb:u,Rb:0,Va:0,ab:b,top:g.top,left:g.left,Le:o,opacity:h.sc(k),Yc:[h.o(),h.j()].join(),ae:[h.Ib(),h.Hb()].join(),width:h.va(k),height:h.ua(k)};s++}}},getWatchCount:function(){return s}}});
V&&V("union/preview",["union/common/bom","union/common/logic","union/common/cookie"],function(f,g,e){function i(c){c=decodeURIComponent(c).replace(/\\x1e/g,"&").replace(/\\x1d/g,"=").replace(/\\x1c/g,"?").replace(/\\x5c/g,"\\");return g.Id(c)}function d(c,d){var b;b=d?d.substring(d.indexOf("?")):f.S(window)?window.location.search.slice(1):window.top.location.search.slice(1);var a=document.referrer,j=0<=c.indexOf("inlay")||"ui"===c?"bd_cpro_prev":"bd_cpro_fprev",h="",p;try{p=document.cookie}catch(i){}-1!==
b.indexOf(j)&&(h=g.uc(b,j));!h&&p&&-1!==p.indexOf(j)&&(h=e.ga(j));!h&&-1!==a.indexOf(j)&&(h=g.uc(a,j));return h}return{Gb:function(c,e){var b=window.location.href,a=parseInt(c.rsi0,10),j=parseInt(c.rsi1,10),h=parseInt(c.at,10),f=u,g=d(e,b);if(g)if(g=i(g),h===l&&(h=1),1!==parseInt(g.type,10)&&2===(h&2))f=parseInt(g.imgWidth,10)===parseInt(a,10)&&parseInt(g.imgHeight,10)===parseInt(j,10);else if(1===parseInt(g.type,10)&&(1===(h&1)||64===(h&64)||32===(h&32)))f=m;return f?(a=0<=e.indexOf("inlay")||"ui"===
e?"bd_cpro_prev":"bd_cpro_fprev",b=d(e,b),j=c.tn,h=i(b),f=q,0<=e.indexOf("inlay")?f={serviceUrl:"http://cpro.baidu.com/cpro/ui/preview/templates/"+(1===parseInt(h.type,10)?j+".html":2===parseInt(h.type,10)?"image.html":4===parseInt(h.type,10)?"flash.html":"blank_tips.html")+"?",paramString:(""+a+"=#"+b+"&ut="+ +new Date).replace(/\.(?!swf)/g,"%252e")}:"float"===e&&(h=parseInt(h.type,10),h="http://cpro.baidu.com/cpro/ui/preview/templates/"+(2===h?"float_image.html":4===h?"float_flash.html":"blank_tips.html")+
"?",b="tn="+j+("&"+a+"="+b).replace(/\./g,"%252e")+"&ut="+ +new Date,f={serviceUrl:h,paramString:b}),f):q}}});
V&&V("union/business/businessLogic",["union/preview","union/common/dom"],function(f,g){var e={inlay:8,"float":2,patch:2,linkunit:20,popup:1},i={inlay:{},"float":{},patch:{},linkunit:{},popup:{}},d={1001:"inlay-fixed",1002:"inlay-float",2001:"float-left-middle",2002:"float-right-middle",2003:"float-left-bottom",2004:"float-right-bottom",2005:"float-top",2006:"float-bottom",2007:"float-linkunit-left",3001:"patch-webpage",3002:"patch-flash",4001:"captcha-webpage"};return{fb:function(c){var d=c._html||
{},b="",a="http://pos.baidu.com/acom?",j=c.id.split("_")[0],h=parseInt(d.conW||0,10)||parseInt(c._w,10)||parseInt(c.sw,10)||parseInt(d.rsi0,10),e=parseInt(d.conH||0,10)||parseInt(c._h,10)||parseInt(c.sh,10)||parseInt(d.rsi1,10),g=c.displayType,i=d.tn||"",n=i.toLowerCase(),r=d.ch||0,c=c.qn||"",x=d.n||"",B=d.dai||0;d.dtm="BAIDU_DUP2_SETJSONADSLOT";d.dc="2";d.di=j;var b=[],o;for(o in d)o&&d.hasOwnProperty(o)&&b.push(""+o+"="+encodeURIComponent(d[o].toString()));b=b.join("&");if((o=f.Gb(d,g))&&o.serviceUrl!==
l&&o.paramString!==l)a=o.serviceUrl,b=o.paramString;return{slotId:j,slotWidth:h,slotHeight:e,displayType:g,styleType:n,iframeId:"cproIframe_"+j+"_"+d.dai,unionAccount:x,adIndex:B,channel:r,pvId:c,stuffType:"unknown",serviceUrl:a,paramString:b,delayIn:d.delayIn,delayOut:d.delayOut,sessionSync:d.sessionSync!==u&&"false"!==d.sessionSync,closeFor:d.closeFor,xuantingType:d.xuanting,tn:i}},Tb:function(c){var d={};d.dd=(c.dd||"pc").toLowerCase();d.I=(c.I||"inlay-fixed").toLowerCase();d.z=(c.z||"template_inlay_all_normal").toLowerCase();
d.aa=(c.aa||"text").toLowerCase();d.R=c.R;if(-1<d.z.indexOf("tlink")||-1<d.z.indexOf("linkunit"))d.I="linkunit-fixed";0<=d.z.indexOf("float_xuanfuwin")&&(d.I="popup-float");c=d.I.split("-");d.wb=c[0]||"inlay";d.we=c[1]||"fixed";return d},Ta:function(c){var c=this.Tb(c),d=c.wb;return this.ld(c)<e[d]},ld:function(c){var c=this.Tb(c),d=0,c=i[c.wb],b;for(b in c)b&&c[b]&&c.hasOwnProperty(b)&&(g.c(b)?d++:c[b]=l);return d},ib:function(c){c=this.Tb(c);i[c.wb][c.R]=1;return m},Kb:function(c,d){var b=document.getElementById("cpro_"+
c);b||(b=document.getElementById(d));return b},pd:function(c){return d[c]},kb:function(c){var d=c.slotId;U(["viewWatch"],function(b){b.register({id:d,wrapperId:c.iframeId,logType:"block",extra:"ch="+c.channel+"&jk="+c.pvId+"&n="+c.unionAccount})},m)}}});
V&&V("union/common/bom",[],function(){var f={};/msie (\d+\.\d)/i.test(navigator.userAgent)&&(f.d=document.documentMode||+RegExp.$1);/opera\/(\d+\.\d)/i.test(navigator.userAgent)&&(f.opera=+RegExp.$1);/firefox\/(\d+\.\d)/i.test(navigator.userAgent)&&(f.hd=+RegExp.$1);/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(navigator.userAgent)&&!/chrome/i.test(navigator.userAgent)&&(f.$d=+(RegExp.$1||RegExp.$2));/chrome\/(\d+\.\d)/i.test(navigator.userAgent)&&(f.jc=+RegExp.$1);try{/(\d+\.\d)/.test(window.external.Fe)&&
(f.Kd=+RegExp.$1)}catch(g){}f.xc=/webkit/i.test(navigator.userAgent);f.Fd=/gecko/i.test(navigator.userAgent)&&!/like gecko/i.test(navigator.userAgent);f.wc="CSS1Compat"==document.compatMode;return{e:f,H:function(){var e=m;if(this.e.d&&(7>this.e.d||"BackCompat"===document.compatMode))e=u;return e},Ib:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.scrollWidth:e.document.documentElement.scrollWidth}catch(f){return 0}},Hb:function(e){try{return e=e||window,"BackCompat"===
e.document.compatMode?e.document.body.scrollHeight:e.document.documentElement.scrollHeight}catch(f){return 0}},o:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.clientWidth:e.document.documentElement.clientWidth}catch(f){return 0}},j:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.clientHeight:e.document.documentElement.clientHeight}catch(f){return 0}},F:function(e){e=(e||window).document;return window.pageYOffset||e.documentElement.scrollTop||
e.body.scrollTop},Ia:function(e){e=(e||window).document;return window.pageXOffset||e.documentElement.scrollLeft||e.body.scrollLeft},$a:function(e){var f=u;try{e&&"object"===typeof e&&e.document&&"setInterval"in e&&(f=m)}catch(d){f=u}return f},G:function(e){e=e||window;return e!=window.top&&e!=e.parent||!this.$a(e)},S:function(e,f){for(var f=2===arguments.length?f:e.parent,d=0;10>d++&&this.G(e,f);){var c;try{c=!!e.parent.location.toString()}catch(g){c=u}if(!c)return m;e=e.parent}return 10<=d?m:u},
be:function(e,f){var d=new Image,c="cpro_log_"+Math.floor(2147483648*Math.random()).toString(36),f=f||window;f[c]=d;d.onload=d.onerror=d.onabort=function(){d.onload=d.onerror=d.onabort=q;d=f[c]=q};d.src=e},Ha:function(e){if(!e)return document;"string"===typeof e&&(e=document.getElementById(e));return 9===e.nodeType?e:e.ownerDocument||e.document},Y:function(e){"string"===typeof e&&(e=document.getElementById(e));e=this.Ha(e);return e.parentWindow||e.defaultView||q},Be:function(e){e=e||window;return this.G(e)&&
!this.S(e,e.top)&&this.$a(e.top)?e.top:e}}});
V&&V("union/common/cookie",[],function(){return{ga:function(f,g){var e,i=RegExp("(^| )"+f+"=([^;]*)(;|$)").exec((g||window).document.cookie);i&&(e=i[2]);return e},ya:function(f,g,e){var e=e||{},i=e.ra;"number"==typeof e.ra&&(i=new Date,i.setTime(i.getTime()+e.ra));document.cookie=""+f+"="+g+(e.path?"; path="+e.path:"")+(i?"; expires="+i.toGMTString():"")+(e.domain?"; domain="+e.domain:"")+(e.Ne?"; secure":"")},remove:function(f){var g=new Date;g.setTime(g.getTime()-86400);this.ya(f,"",{path:"/",ra:g})}}});
V&&V("union/common/dom",["union/common/oo","union/common/bom"],function(f,g){return f(function(e){var f=g.e;return{c:function(d,c){return"string"===typeof d||d instanceof String?(c||window).document.getElementById(d):d},vc:function(d,c){var f=m;if("string"===typeof c)return d.id===c;if(c.constructor===Object)return e.fd(c,function(a,b){var c=(d.getAttribute?d.getAttribute(b):d[b])||d[b];if("tagName"===b){if(c.toUpperCase()!=a.toUpperCase())return f=u}else if(c!=a)return f=u}),f;if(c.constructor===
Array){var b=c.concat([]);b.reverse();for(var a=d;a&&b.length;a=a.parentNode)this.vc(a,b[0])&&b.shift();return!b.length?m:u}},Lc:function(d,c){if(d&&c(d)!==u){var e=d.childNodes;if(e)for(var b=0,a=e.length;b<a;b++)if(this.Lc(e[b],c)===u)return u}},Ic:function(d,c){var e=this;d.constructor===Object&&(d=this.v(d));if("string"===typeof c){for(var b=document.getElementById(c),a=b;a;){if(a===d)return b;a=a.parentNode}return q}if(c.constructor===Object){var j=q;e.Lc(d,function(a){if(e.vc(a,c))return j=
a,u});return j}},v:function(d){if(d){if(d.nodeName)return d;1<arguments.length&&(d=Array.prototype.slice.call(arguments,0));if("string"===typeof d)return document.getElementById(d);if(d.constructor===Object)return this.Ic(document.documentElement,d);if(d.constructor===Array){for(var c=d.concat([]),e=document.documentElement;c.length&&e;)e=this.Ic(e,c.shift());return e}}},Yd:function(d,c,g){var g=g||this.Se||window,b=g.document;this.nc=0;this.wa=this.wa||[];this.wa.push({Cb:d,mc:c||0,xb:u});var a=
e.k(function(){var a=u;this.nc++;var c=u;try{g.frameElement&&(c=m)}catch(d){c=m}if(f.d&&9>f.d&&!c)try{b.documentElement.doScroll("left"),a=m}catch(e){}else if("complete"===b.readyState||this.ed)a=m;else if(3E5<this.nc){this.da&&(g.clearInterval(this.da),this.da=q);return}if(a)try{if(this.wa&&this.wa.length)for(var a=0,s=this.wa.length;a<s;a++){var n=this.wa[a];n&&n.Cb&&!n.xb&&(n.mc?(n.xb=m,g.setTimeout(n.Cb,n.mc)):(n.xb=m,n.Cb()))}}catch(r){throw r;}finally{this.da&&(g.clearInterval(this.da),this.da=
q)}},this),d=e.k(function(){this.ed=m;a()},this);this.da||(this.da=g.setInterval(a,50),b.addEventListener?(b.addEventListener("DOMContentLoaded",d,u),g.addEventListener("load",d,u)):b.attachEvent&&g.attachEvent("onload",d,u))},H:function(){var d=m;if(f.d&&(7>f.d||"BackCompat"===document.compatMode))d=u;return d},bind:function(d,c,e){"string"===typeof d&&(d=this.v(d));c=c.replace(/^on/i,"").toLowerCase();d.addEventListener?d.addEventListener(c,e,u):d.attachEvent&&d.attachEvent("on"+c,e);return d},
Mc:function(d,c,e){d=this.v(d);if(!d)return q;c=c.replace(/^on/i,"").toLowerCase();d.removeEventListener?d.removeEventListener(c,e,u):d.detachEvent&&d.detachEvent("on"+c,e);return d},s:function(d,c){var e;"string"===typeof d&&(d=this.v(d));var b=g.Ha(d),a="",a=-1<c.indexOf("-")?c.replace(/[-_][^-_]{1}/g,function(a){return a.charAt(1).toUpperCase()}):c.replace(/[A-Z]{1}/g,function(a){return"-"+a.charAt(0).toLowerCase()});b&&b.defaultView&&b.defaultView.getComputedStyle?((b=b.defaultView.getComputedStyle(d,
q))&&(e=b.getPropertyValue(c)),"boolean"!==typeof e&&!e&&(e=b.getPropertyValue(a))):d.currentStyle&&((b=d.currentStyle)&&(e=b[c]),"boolean"!==typeof e&&!e&&(e=b[a]));return e},X:function(d,c){c=c||window;"string"===typeof d&&(d=this.v(d));if(d){for(var e=this.ea(d),b,a=0;c!=c.parent&&10>a;)a++,b=this.ea(c.frameElement),e.left+=b.left,e.top+=b.top,c=c.parent;return e}},ea:function(d){"string"===typeof d&&(d=this.v(d));var c=g.Ha(d),e=g.e;0<e.Fd&&c.getBoxObjectFor&&this.s(d,"position");var b={left:0,
top:0},a;if(d==(e.d&&!e.wc?c.body:c.documentElement)||!d)return b;if(d.getBoundingClientRect)d=d.getBoundingClientRect(),b.left=Math.floor(d.left)+Math.max(c.documentElement.scrollLeft,c.body.scrollLeft),b.top=Math.floor(d.top)+Math.max(c.documentElement.scrollTop,c.body.scrollTop),b.left-=c.documentElement.clientLeft,b.top-=c.documentElement.clientTop,d=c.body,c=parseInt(this.s(d,"borderLeftWidth"),10),d=parseInt(this.s(d,"borderTopWidth"),10),e.d&&!e.wc&&(b.left-=isNaN(c)?2:c,b.top-=isNaN(d)?2:
d);else{a=d;do{b.left+=a.offsetLeft;b.top+=a.offsetTop;if(0<e.xc&&"fixed"==this.s(a,"position")){b.left+=c.body.scrollLeft;b.top+=c.body.scrollTop;break}a=a.offsetParent}while(a&&a!=d);if(0<e.opera||0<e.xc&&"absolute"==this.s(d,"position"))b.top-=c.body.offsetTop;for(a=d.offsetParent;a&&a!=c.body;){b.left-=a.scrollLeft;if(!e.opera||"TR"!=a.tagName)b.top-=a.scrollTop;a=a.offsetParent}}return b},va:function(d,c){var d=this.v(d),e=d.offsetWidth;if(c||u)var b=this.s(d,"marginLeft").toString().toLowerCase().replace("px",
"").replace("auto","0"),a=this.s(d,"marginRight").toString().toLowerCase().replace("px","").replace("auto","0"),e=e+(parseInt(b||0,10)+parseInt(a||0,10));return e},ua:function(d,c){var d=this.v(d),e=d.offsetHeight;if(c||u)var b=this.s(d,"marginTop").toString().toLowerCase().replace("px","").replace("auto","0"),a=this.s(d,"marginBottom").toString().toLowerCase().replace("px","").replace("auto","0"),e=e+(parseInt(b||0,10)+parseInt(a||0,10));return e},Ae:function(d){var d=this.v(d),c=this.Y(d),e=0;if(this.G(window)&&
!g.S(window)){for(;c.parent!=window.top&&10>e;)e++,c=c.parent;10>e&&(d=c.frameElement||d)}return d},Fb:function(d){var c=this.v(d),d=this.Y(c),e=100,b;try{for(;c&&c.tagName;){b=100;if(this.e.d){if(5<this.e.d)try{b=c.ye.alpha.opacity||100}catch(a){}e=e>b?b:e}else{try{b=100*(d.getComputedStyle(c,q).opacity||1)}catch(j){}e*=b/100}c=c.parentNode}}catch(h){}return e||100},sc:function(d){for(var c=this.v(d),d=this.Y(c),c=this.Fb(c),e=100,b=0;this.G(d);){b++;if(g.S(d,d.parent))break;else e=100,d.frameElement&&
(e=this.Fb(d.frameElement)),c*=e/100;d=d.parent}return c}}})});
V&&V("union/common/logic",[],function(){return{xe:function(f){(f=f||"")&&(f=f.replace(/%u[\d|\w]{4}/g,function(f){return encodeURIComponent(unescape(f))}));return f},ia:function(f,g){return f.replace(/{(.*?)}/g,function(e,f){return g[f]||""})},Id:function(f){return(new Function("return "+f))()},uc:function(f,g){if(f&&g){var e=f.match(RegExp("(^|&|\\?|#)"+g+"=([^&]*)(&|$)",""));if(e)return e[2]}return q},Ie:function(f,g){var f=f||"",g=g||"?",e=arguments.callee;e.hasOwnProperty[g]||(e[g]={});e=e[g];
if(e.hasOwnProperty(f))return e[f];var i={},d=f.indexOf(g),c=f.substring(d+1).split("&");if(-1!==d)for(var d=0,k=c.length;d<k;d++){var b=c[d].split("="),a=decodeURIComponent(b[0]),b=decodeURIComponent(b[1]);i.hasOwnProperty(a)?(i[a].constructor!==Array&&(i[a]=[i[a]]),i[a].push(b)):i[a]=b}return e[f]=i}}});
V&&V("union/common/oo",[],function(){function f(d){var c=f.create(f);return d.call(c,c,c.gc)}function g(d,c){if(d.constructor===Array)for(var e=0,b=d.length;e<b;e++){if(c.call(d,d[e],e,d)===u)return u}else{var e=!{toString:1}.propertyIsEnumerable("toString"),a="toString,toLocaleString,valueOf,constructor,propertyIsEnumerable,hasOwnProperty,isPrototypeOf".split(",");for(b in d)if(d.hasOwnProperty(b)&&c.call(d,d[b],b,d)===u)return u;if(e){e=0;for(b=a.length;e<b;e++){var j=a[e];if(d.hasOwnProperty(j)&&
c.call(d,j,e,d)===u)return u}}}return m}function e(d,c,e){g(c,function(b,a){if(!d.hasOwnProperty(a)||e)d[a]=b})}function i(d){function c(){}if(Object.create)return Object.create(d);c.prototype=d;return new c}f.gc={};f.create=i;f.fd=g;f.pb=function(d){var c,f=d.hasOwnProperty("constructor")?d.constructor:function(){};f.prototype=d;f.prototype.constructor=f;c=c||{};c.Xb&&e(f,c.Xb);return f};f.extend=function(d,c,f){var b;b=c.hasOwnProperty("constructor")?c.constructor:function(){d.constructor.apply(this,
arguments)};b.prototype=i(d.prototype);e(b.prototype,c,m);b.prototype.constructor=b;b.prototype.se=d.prototype;e(b,d);f=f||{};f.Xb&&e(b,f.Xb,m);return b};f.Ge=function(d){var c=this.gc;g(d.split("."),function(d){c.hasOwnProperty(d)||(c[d]={});c=c[d]});return c};f.k=function(d,c){var e;return function(){e=e||[];for(var b=0,a=arguments.length;b<a;b++)e.push(arguments[b]);return d.apply(c||{},e)}};return f});
V&&V("union/DynamicFloatDecorator",["union/common/bom","union/common/dom","union/common/cookie","union/common/oo"],function(f,g,e,i){var d=window,c;i(function(k){c=k.pb({constructor:function(b){this.Ob(b);this.Cd();this.Dd()},Ob:function(b){this.r=b.r;this.ca=b.ca;this.M=5;this.a=g.c(this.r);this.Nc=g.c(b.re);this.Ba=g.c(b.pe);this.f=b.f;this.l=b.l||0;0>this.l&&(this.l=0);this.Q="bd_close_"+b.g;e.ga(this.Q,d);if(this.f&&(this.tb=500,this.na=u,this.Pa=m,this.A=b.A||0,this.B=b.B||0,0>this.A&&(this.A=
0),0>this.B&&(this.B=0),this.w=b.w||u))this.l=0;this.h=b.h;var a=g.c(this.ca);0===this.h?a&&a.getAttribute("_src")&&a.setAttribute("src",a.getAttribute("_src")):isNaN(this.h)?a.parentNode.removeChild(a):(this.Ra=b.Ra?b.Ra:0,this.ka=b.ka?b.ka:0,this.Z=b.Z||u)},Cd:function(){if(!this.Z){var b=g.H(),a;if(this.h){a=1;if(2===this.h)this.f="top",a=2;else if(3===this.h)this.f="bottom",a=1;else if(1!=this.h&&0!=this.h&&this.a){this.a.style.display="none";return}for(var c=1;2>=c;c++)(function(a){var b="bkimg_"+
+new Date+Math.floor(1E5*Math.random()),c=window[b]=new Image;c.onload=c.onerror=function(){c.onload=c.onerror=q;c=window[b]=q};c.src="http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk"+a+".png"})(c);this.f&&!b&&this.a&&document.body.appendChild(this.a);var c=2===this.h||3===this.h,e=1<this.h?"display:none;":"",p=1===this.h?"width:"+this.Ra+"px;":"";this.f&&!b&&(p=f.o(window)+"px");var i;g.H()?2===this.h?i="position:fixed;top:0;width:100%;":3===this.h&&(i="position:fixed;bottom:0;width:100%;"):
2===this.h?i="position:absolute;top:0;width:100%;":3===this.h&&(i="position:absolute;top:"+(f.F(d)+f.j(d)-this.Ra)+"px;width:100%;");b="";f.e.d&&7>f.e.d&&(b="_background-image:none;_filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk"+a+".png');");if(this.a){var s="",n="";c&&(s='<div id="'+this.r+'Toggle" style="z-index:2147483646;cursor:pointer;position:absolute;right:0;'+this.f+':0;width:40px;height:100%;background-color:#3f3f3f;"><div style="width:20px;height:22px;position:absolute;top:50%;margin-top:-11px;left:50%;margin-left:-10px;background:no-repeat url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk'+
a+".png);"+b+'"></div></div>',n='<div id="'+this.r+'Bk" style="'+this.f+':0;left:0;position:absolute;width:100%;height:100%;background-color:#666;-moz-opacity:.6;filter:alpha(opacity=60);opacity:.6;"></div>');var k="position:relative;margin:5px 0;";this.a.insertAdjacentHTML("afterBegin",n+s);a=this.a.getElementsByTagName("IFRAME")[0]}else a=g.c(this.ca);c&&(this.nb=document.getElementById(this.r+"Toggle"),this.ob=this.nb.getElementsByTagName("DIV")[0],this.f&&this.a.setAttribute("dockTo",this.f),
this.ba=document.getElementById(this.r+"Bk"),this.ba.style.height=this.ka+10+"px",this.nb.style.height=this.ka+10+"px",this.a.style.cssText=e+p+"height:"+(this.ka+10)+"px;right:0;z-index:2147483646;text-align:center;font-size:0;_overflow-y:hidden;"+i,a.style.cssText=k);this.U()}}},Dd:function(){g.Yd(i.k(this.Md,this));g.bind(d,"scroll",i.k(this.U,this));g.bind(d,"resize",i.k(this.U,this));this.Z&&g.bind(d,"onorientationchange"in window?"orientationchange":"resize",i.k(this.U,this));this.nb&&g.bind(this.nb,
"click",i.k(this.$b,this));this.Nc&&g.bind(this.Nc,"click",i.k(this.qe,this));this.Ba&&g.bind(this.Ba,"click",i.k(this.oe,this))},Md:function(){if(this.a){var b=this;this.a.setAttribute("baiduxuanting","baiduCproXuantingRoof");this.f&&(e.ga(this.Q,d)?this.a.parentNode.removeChild(this.a):(setTimeout(function(){if(b.a){var a=g.c(b.ca);a.getAttribute("_src")&&a.setAttribute("src",a.getAttribute("_src"));b.a.style.display="block"}},this.A),this.B&&setTimeout(function(){b.a&&(b.a.style.display="none",
b.a.parentNode.removeChild(b.a))},this.A+this.B)))}},jb:function(){var b={path:""};if(this.l){var a=new Date;a.setTime(a.getTime()+this.l);b.ra=a}e.ya(this.Q,1,b)},qe:function(){this.a&&(this.a.parentNode.removeChild(this.a),e.remove(this.Q),(this.w||this.l)&&this.jb(),document.body.removeChild(g.c(this.ca+"Wrap_placeholder")))},oe:function(){var b=g.c(this.ca);"hidden"===b.parentNode.style.visibility?(b.parentNode.style.visibility="visible",this.Ba.style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/2.0.0/lu_shouqi.png)",
this.Ba.innerHTML="\u6536\u8d77"):(b.parentNode.style.visibility="hidden",this.Ba.style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/2.0.0/lu_logo.png)",this.Ba.innerHTML="")},$b:function(){this.Pa?this.Lb():this.show()},Na:function(b){if(!this.na){this.na=m;var a=this.ba,c=g.c(this.ca),d=this.f,e=this.a.offsetHeight,i=Math.round(this.tb/e),s=0;b&&(this.a.style.width="100%");var n=+new Date,k=this,x=setInterval(function(){var g=s=Math.round((+new Date-n)/i),o=g;b&&(o=e-g);
a.style[d]=-o+"px";c.style[d]=-o+"px";g>=e&&(this.na=u,(k.Pa=b)&&"top"===d||!b&&"bottom"===d?f.e.d&&7>f.e.d?this.ob.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk2.png');":this.ob.style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk2.png)":f.e.d&&7>f.e.d?this.ob.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk1.png');":
this.ob.style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk1.png)",o=e,b&&(o=0),a.style[d]=-o+"px",c.style[d]=-o+"px",clearInterval(x))},i)}},show:function(){this.w&&e.remove(this.Q);this.Na(m)},Lb:function(){(this.w||this.l)&&this.jb();this.Na(u)},U:function(){var b=f.o(d);this.f&&!this.Z&&(this.a&&(this.a.style.width=b+"px"),this.ba&&(this.ba.style.width=b+"px"));this.Dc&&clearTimeout(this.Dc);this.Dc=setTimeout(i.k(this.Ka,this),5)},Ka:function(){g.s(document.body,
"position");if(g.H()){this.a.style.zIndex=2147483646;if(1===this.h)if("fixed"===this.a.style.position)this.Ca(),this.Ed()&&(this.a.style.cssText=q,this.Ub());else{var b=this.bc();b&&(this.Ea(),this.a.style.position="fixed",this.a.style.top=b+"px",this.Ca())}4===this.h&&(this.ja||(this.ja=this.a.style.bottom.replace("px","")),this.a.style.bottom=361>f.j()?Math.min(60,this.ja)+"px":this.ja+"px")}else this.xa(this.r)},Ea:function(){var b=this.r+"placeholder",a=document.createElement("div");a.id=b;a.align&&
(a.align=this.a.getAttribute("align"));a.style.width=this.a.getAttribute("width")+"px";a.style.height=this.a.getAttribute("height")+"px";a.style.margin="0";a.style.padding="0";a.style.background="none";a.style.border="none";this.a.parentNode.insertBefore(a,this.a);return m},Ub:function(){var b=document.getElementById(this.r+"placeholder");b.parentNode.removeChild(b);return m},bc:function(){return 5>this.q(this.a).top?5:u},Hd:function(){return 5>this.q(this.a).top?5:u},Ed:function(){var b=document.getElementById(this.r+
"placeholder");return this.a&&b&&(b=this.q(b).V.top,this.q(this.a).V.top<=b)?m:u},Ca:function(){var b=document.getElementById(this.r+"placeholder");this.a&&b&&(this.a.style.left=this.q(b).left+"px")},q:function(b){var a=g.ea(b),c=g.Ia(d),e=g.F(d),f=g.va(b,u),b=g.ua(b,u);return{top:a.top-e,bottom:a.top-e+b,left:a.left-c,right:a.left-c+f,V:{top:a.top,bottom:a.top+b,left:a.left,right:a.left+f}}},xa:function(){var b=f.F(d),a=g.s(d.document.body,"position").toString(),c=g.ea(d.document.body),e=c.left,
p=c.top;if(c=document.getElementById(this.r))if(c.style.position="absolute",c.style.zIndex=2147483646,1===this.h)if(document.getElementById(this.r+"placeholder")){var i=document.getElementById(this.r+"placeholder"),s=this.q(i);c.style.top=b+this.M+"px";c.style.left=s.V.left+"px";"relative"===a&&(c.style.top=b+this.M-p+"px",c.style.left=s.V.left-e+"px");c.style.visibility="visible";b=this.q(c);s.V.top>=b.V.top&&(c.parentNode.removeChild(c),i.parentNode.insertBefore(c,i),i.parentNode.removeChild(i),
c.style.cssText=q)}else{if(i=this.Hd())this.M=i,this.Ea(this.r),i=document.getElementById(this.r+"placeholder"),s=this.q(i),c.parentNode.removeChild(c),document.body.appendChild(c),c.style.zIndex=2147483646,c.style.top=b+this.M+"px",c.style.left=s.V.left+"px","relative"===a&&(c.style.top=b+this.M-p+"px",c.style.left=s.V.left-e+"px"),c.style.visibility="visible",c.style.position="absolute"}else 2===this.h?c.style.top=b+"px":3===this.h?c.style.top=b+f.j()-(this.ka+10)+"px":4===this.h&&(this.ja||(this.ja=
this.a.style.bottom.replace("px","")),this.a.style.bottom=361>f.j()?Math.min(60,this.ja)+b+"px":this.ja+b+"px")}})});return{me:function(d){new c(d)}}});
V&&V("nova/painter/inlayFixed1392089005",["union/business/businessLogic"],function(f){function g(e){return'<iframe id="{iframeId}" width="{slotWidth}" height="{slotHeight}" src="{serviceUrl}{paramString}" align="center,center" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" allowtransparency="true"></iframe>'.replace(/{(.*?)}/g,function(f,d){return e[d]||""})}return{render:function(e,i){e.displayType="inlay-fixed";var d=f.fb(e),c=f.Kb(d.slotId,i),k={I:d.displayType,z:d.styleType,aa:d.stuffType,
R:d.iframeId};if(!f.Ta(k))return u;c.innerHTML=g(d);f.ib(k);f.kb(d,i)}}});
V&&V("nova/painter/xuanting1392089005","union/common/cookie,union/common/bom,union/common/dom,union/common/logic,union/common/oo,union/business/businessLogic".split(","),function(f,g,e,i,d,c){var k;d(function(b){k=b.pb({constructor:function(a){var b=a.Qa.id;this.Qa=e.v(a.Qa);this.type=+a.type;this.src=a.src;this.width=a.width;this.height=a.height;this.z=a.z||"";this.Yb=a.Yb||"";this.pa=a.pa||"0";this.Aa=a.Aa||"";this.La=a.La||"";this.M=this.ac=5;this.L=a.L;this.T=a.T;this.g=a.g;this.Q="bd_close_"+
this.g;this.ke=!!f.ga(this.Q);this.b=this.ud(this.g);this.u=b;this.f="";this.fileName="c";this.Sa=a.Sa||0;this.backgroundColor=a.backgroundColor;this.Da=a.Da;2===this.type?this.f="top":3===this.type&&(this.f="bottom");this.f&&(this.Pa=m,this.A=+a.A||0,this.B=+a.B||0,this.w=!!a.w||u,this.l=+a.l||0,this.tb=500);this.Z=a.Z||u},Ce:function(a){return"string"===typeof a?document.getElementById(a):a},he:function(a,b){return(b||document).getElementsByTagName(a)[0]},Kc:function(a,b){return a.replace(/\{(.*?)\}/g,
function(a,c){return b.hasOwnProperty(c)?b[c]:a})},ud:function(a){return"cproIframe_"+a},e:g.e,jb:function(){var a={path:""};if(this.l&&!this.w){var b=new Date;b.setTime(b.getTime()+this.l);a.ra=b}f.ya(this.Q,1,a)},Zd:function(a){var b=new Date;b.setTime(b.getTime()-86400);f.ya(a,"",{path:"/",ra:b})},U:function(){this.clientWidth=g.o(window);this.clientHeight=g.j(window);this.f&&(this.t&&(this.t.style.width=this.clientWidth+"px"),this.ba&&(this.ba.style.width=this.clientWidth+"px"));this.Ma&&clearTimeout(this.Ma);
this.Ma=setTimeout(b.k(this.Ka,this),5)},Ka:function(){var a=this.t;if(a)if(e.H()){if(a.style.zIndex=2147483646,1===this.type)if("fixed"==a.style.position)this.Ca(),this.Uc()&&(a.style.cssText=q,this.Ub());else{var b=this.bc();b&&(this.Ea(),a.style.position="fixed",a.style.top=b+"px",this.Ca())}}else this.xa(this.t)},Uc:function(a){var b;a?(b=document.getElementById(a),a=document.getElementById(""+a+"placeholder")):(b=this.t||document.getElementById(this.u),a=document.getElementById(""+this.u+"placeholder"));
return b&&a&&(a=this.q(a).mb,this.q(b).mb<=a)?m:u},Ca:function(a){var b;a?(b=document.getElementById(a),a=document.getElementById(""+a+"placeholder")):(b=this.t||document.getElementById(this.u),a=document.getElementById(""+this.u+"placeholder"));b&&a&&(a=this.q(a).left,b.style.left=a+"px")},q:function(a){var b=e.ea(a),c=g.Ia(window),d=g.F(window),f=e.va(a,u),a=e.ua(a,u);return{top:b.top-d,bottom:b.top-d+a,left:b.left-c,right:b.left-c+f,mb:b.top,ue:b.top+a,eb:b.left,Me:b.left+f}},xa:function(){this.clientWidth=
g.o(window);this.clientHeight=g.j(window);var a=g.F(window),b=e.s(document.body,"position").toString(),c=e.ea(document.body),d=c.left,f=c.top;if(c=this.t)if(c.style.position="absolute",c.style.zIndex=2147483646,1===this.type)if(document.getElementById(""+this.u+"placeholder")){var i=document.getElementById(""+this.u+"placeholder"),n=this.q(i);c.style.top=""+(a+this.M)+"px";c.style.left=""+n.eb+"px";"relative"==b&&(c.style.top=a+this.M-f+"px",c.style.left=n.eb-d+"px");c.style.visibility="visible";
a=this.q(c);n.mb>=a.mb&&(c.parentNode.removeChild(c),i.parentNode.insertBefore(c,i),i.parentNode.removeChild(i),c.style.cssText=q)}else{if(i=this.ie(this.u))this.M=i,this.Ea(this.u),i=document.getElementById(""+this.u+"placeholder"),n=this.q(i),c.parentNode.removeChild(c),document.body.appendChild(c),c.style.zIndex=2147483646,c.style.top=a+this.M+"px",c.style.left=n.eb+"px","relative"==b&&(c.style.top=a+this.M-f+"px",c.style.left=n.eb-d+"px"),c.style.visibility="visible",c.style.position="absolute"}else 2===
this.type?c.style.top=a+"px":3===this.type&&(c.style.top=a+this.clientHeight-(this.height+10)+"px")},Vb:function(){if(!this.Z){var a=this.type,b=this.width,c=this.height,d={srcAttrName:a===l||1==a?"src":"_src",iframeWidth:b,iframeHeight:c,iframeId:this.b,paramString:this.L||"",serviceUrl:this.T};this.Td();var f=u;if(a&&(1===a||2===a||3===a)){var g=f="auto",i;if(1===a)i="inline-block",f=b+"px",g=c+"px";else if(2===a||3===a)i="block",f="100%",g=+c+10+"px";d.widthValue=f;d.heightValue=g;d.displayValue=
i;a=this.Qa;a.setAttribute("width",f);a.setAttribute("height",g);a.style.cssText=this.Kc("width:{widthValue};height:{heightValue};display:{displayValue};",d);f=m}d=this.Kc('<iframe id="{iframeId}" {srcAttrName}="{serviceUrl}{paramString}" width="{iframeWidth}" height="{iframeHeight}" align="center,center" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" allowtransparency="true" ></iframe>',d);this.Qa.innerHTML=d;this.Ya=e.v(this.b);f&&(this.t=this.Ya.parentNode);this.bd();this.je()}},
bd:function(){var a=this.type,b=this.Ya,c=this.t;if(a){var d=1;if(2===a)d=2;else if(3===a)d=1;else if(1!==a&&0!==a&&this.t){this.t.style.display="none";return}var f=2===a||3===a,i="";switch(a){case 2:case 3:var i="display:none;",n="";this.e.d&&7>this.e.d&&(n="_background-image:none;_filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk"+d+".png');");d=f?'<div id="'+this.b+'WrapToggle" style="z-index:2147483646;cursor:pointer;position:absolute;right:0;'+
this.f+":0;width:40px;height:100%;background-color:"+this.backgroundColor+';"><div style="width:20px;height:22px;position:absolute;top:50%;margin-top:-11px;left:50%;margin-left:-10px;background:no-repeat url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk'+d+".png);"+n+'"></div></div>':"";f=f?'<div id="'+this.b+'WrapBk" style="'+this.f+":0;left:0;position:absolute;width:100%;height:100%;background-color:"+this.backgroundColor+";-moz-opacity:"+this.Da/100+";filter:alpha(opacity="+this.Da+
");opacity:"+this.Da/100+';"></div>':"";n="";e.H()?1===a?n="position:fixed;top:0;":2===a?n="position:fixed;top:0;width:100%;":3===a&&(n="position:fixed;bottom:0;width:100%;"):1===a?n="position:absolute;top:0;":2===a?n="position:absolute;top:0;width:100%;":3===a&&(n="position:absolute;top:"+(g.F(window)+g.j(window)-this.width)+"px;width:100%;");c.insertAdjacentHTML("afterBegin",f+d);c.style.cssText=[i,"height:",this.height+10,"px;right:0;z-index:2147483646;text-align:center;font-size:0;_overflow-y:hidden;",
n].join("");b.style.cssText="position:relative;margin:5px 0;";this.Zb=e.v(""+this.b+"WrapToggle");this.lb=this.he("DIV",this.Zb);this.ba=e.v(this.b+"WrapBk");this.U()}}},kb:function(){var a=this.g,b=this.u,c=this;U(["viewWatch"],function(d){d.register({id:a,wrapperId:b,logType:"block",extra:"ch="+c.pa+"&jk="+c.La+"&n="+c.Aa})},m)},je:function(){var a=this,c=a.t,d=a.type,f=a.Ya,a=this;this.f?this.ke?c.parentNode.removeChild(c):(setTimeout(function(){c.style.display="block";if(2===d||3===d){var b=f.getAttribute("_src");
b&&(f.setAttribute("src",b),f.removeAttribute("_src"),a.kb())}},this.A),this.B&&setTimeout(function(){c.style.display="none"},this.A+this.B)):this.kb();this.Zb&&(2===this.type||3===this.type)&&e.bind(this.Zb,"click",b.k(this.$b,this));e.bind(window,"scroll",b.k(this.Ka,this));e.bind(window,"resize",b.k(this.Ka,this))},Td:function(){for(var a=1;2>=a;a++)(function(a){var b="bkimg_"+ +new Date+Math.floor(1E5*Math.random()),c=window[b]=new Image;c.onload=c.onerror=function(){c.onload=c.onerror=q;c=window[b]=
q};c.src="http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk"+a+".png"})(a)},$b:function(){this.Pa?this.Lb():this.show()},Na:function(a){if(!this.na){this.na=m;var b=this.t,c=this.ba,d=this.Ya,e=this.f,f=b.offsetHeight,g=Math.round(this.tb/f),i=0,k=this;a&&(b.style.width="100%");var B=+new Date,o=setInterval(function(){var b=i=Math.round((+new Date-B)/g),j=b;a&&(j=f-b);c.style[e]=-j+"px";d.style[e]=-j+"px";b>=f&&(k.na=u,(k.Pa=a)&&"top"===e||!a&&"bottom"===e?k.e.d&&7>k.e.d?k.lb.style.filter=
"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk2.png');":k.lb.style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk2.png)":k.e.d&&7>k.e.d?k.lb.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk1.png');":k.lb.style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk1.png)",j=f,a&&
(j=0),c.style[e]=-j+"px",d.style[e]=-j+"px",clearInterval(o))},g)}},show:function(){(this.w||this.l)&&this.Zd(this.Q);this.Na(m)},Lb:function(){(this.w||this.l)&&this.jb();this.Na(u)},Ea:function(a){var b;a?(b=document.getElementById(a),a+="placeholder"):(b=this.t||document.getElementById(this.u),a=this.u+"placeholder");var c=document.createElement("div");c.id=a;c.align&&(c.align=b.getAttribute("align"));c.style.width=""+parseInt(b.getAttribute("width"),10)+"px";c.style.height=""+parseInt(b.getAttribute("height"),
10)+"px";c.style.margin="0";c.style.padding="0";c.style.background="none";c.style.border="none";1===this.type&&(c.style.display="inline-block");b.parentNode.insertBefore(c,b);return m},Ub:function(a){a=document.getElementById(a?a+"placeholder":this.u+"placeholder");a.parentNode.removeChild(a);return m},bc:function(a){var b=this.ac;return this.q(a?document.getElementById(a):this.t||document.getElementById(this.u)).top<b?b:u},ie:function(a){var b=this.ac;return this.q(a?document.getElementById(a):this.t||
document.getElementById(this.u)).top<b?b:u}})});return{render:function(b,a){switch(parseInt(b._html.xuanting,10)){case 1:b.displayType="inlay-float";break;case 2:b.displayType="float-top";break;case 3:b.displayType="float-bottom";break;default:b.displayType="inlay-float"}var d=c.fb(b);d.backgroundColor=b._html.rss1||"#666";d.backgroundOpacity=parseInt(b._html.opacity||60,10);var e=c.Kb(d.slotId,a),f={I:d.displayType,z:d.styleType,aa:d.stuffType};if(!c.Ta(f))return u;(new k({Qa:e,g:d.slotId,type:d.xuantingType,
src:"",width:d.slotWidth,height:d.slotHeight,backgroundColor:d.backgroundColor,Da:d.backgroundOpacity,z:d.styleType,Yb:d.tn,pa:d.channel,Aa:d.unionAccount,Sa:d.adIndex,La:d.pvId,A:d.delayIn,B:d.delayOut,w:d.sessionSync,l:d.closeFor,L:d.paramString,T:d.serviceUrl})).Vb();c.ib(f)}}});
V&&V("union/floatad","union/common/oo,union/common/cookie,union/common/dom,union/common/bom,union/common/logic,union/business/businessLogic,union/preview".split(","),function(f,g,e,i,d,c,k){function b(a,b,d){if(!a||!a._html)return q;var e=c.pd(b),f=a._html,g="",j="http://pos.baidu.com/acom?",i=a.id.split("_")[0],o=parseInt(f.conW||0,10)||parseInt(f.rsi0,10)||parseInt(a._w,10)||parseInt(a.sw,10),a=parseInt(f.conH||0,10)||parseInt(f.rsi1,10)||parseInt(a._h,10)||parseInt(a.sh,10),g=f.tn||"",y=g.toLowerCase(),
z=f.n||"",A=parseInt(f.ch||0,10),F=parseInt(f.dai||0,10);f.dtm="BAIDU_DUP2_SETJSONADSLOT";f.dc="2";f.di=i;f.distp=b;0<=g.indexOf("float")&&(f.tn="template_float_all_normal");var g=[],v;for(v in f)v&&f.hasOwnProperty(v)&&g.push(""+v+"="+encodeURIComponent(f[v].toString()));g=g.join("&");if((v=k.Gb(f,e))&&v.serviceUrl!==l&&v.paramString!==l)j=v.serviceUrl,g=v.paramString;return{g:i,Gc:o,Fc:a,I:e,Bb:parseInt(f.rsi6,10),Ab:parseInt(f.rsi7,10),vb:parseInt(f.ccw,10),ub:parseInt(f.ct,10),Ga:parseInt(f.pt,
10),sa:d,J:parseInt(f.fa,10),kd:parseInt(f.flw,10),Qe:f.tn,gb:f.qn,z:y,T:j,L:g,b:"cproIframe"+(b||parseInt(100+100*Math.random(),10)),Aa:z,pa:A,Sa:F,aa:"unknown"}}function a(a){var b=a.slotId;U(["viewWatch"],function(c){c.register({id:b,wrapperId:a.b,logType:"block",extra:"ch="+a.pa+"&jk="+a.gb+"&n="+a.Aa})},m)}var j;f(function(a){j=a.pb({jd:{1:{fc:1,ec:150},2:{fc:0,ec:40},3:{fc:0,ec:0}},constructor:function(b){this.b=b.b;this.T=b.T;this.L=b.L;this.R=this.b+"holder";this.J=b.J;this.sa=b.sa;this.Ga=
b.Ga;this.qc=b.kd;this.W=b.Gc;this.la=b.Fc;this.rb=b.Gc;this.qb=b.Fc;this.gb=b.gb;this.Bb=b.Bb;this.Ab=b.Ab;this.vb=b.vb;this.la+=20;this.lc=1===this.J?0:5;this.W+=10;this.la+=10;this.Jc=this.jd;this.ub=b.ub;this.g=b.g;this.H=i.H();e.bind(window,"resize",a.k(this.U,this));e.bind(window,"scroll",a.k(this.U,this))},Vb:function(){var b=document.createElement("div");b.style.cssText=["maring:0;padding:0;display:block;visibility:visible;border:none;background:none;float:none;overflow:hidden;position:absolute;",
"z-index:"+(1===this.J?2147483646:2147483647)+";","width:"+this.W+"px;","height:"+(this.la+this.lc)+"px"].join("");b.id=this.R;var c="",e=document.createElement("div");e.id=this.b+"CloseBtnWrap";var f=document.createElement("div");f.id=this.b+"CloseBtn";1===this.J?(e.style.cssText=["position:absolute;top:275px;left:0;cursor:pointer;","width:"+this.W+"px;","height:28px;z-index:100;opacity:0;filter:alpha(opacity=0);background-color:#999999;"].join(""),f.style.cssText=["position:absolute;","width:"+
this.W+"px;","height:20px;top:280px;left:0;cursor:pointer;background-color:#999999;color:#fff;font-size:12px;font-family: \u5fae\u8f6f\u96c5\u9ed1;text-align:center;line-height:20px;"].join(""),f.innerHTML="\u5173\u95ed"):(e.style.cssText=["position:absolute;top:0px;","left:"+(this.W-61)+"px;","cursor:pointer;width:61px;height:20px;z-index:100;opacity:0;filter:alpha(opacity=0);background-color:#999999;margin:0;paddong:0;"].join(""),f.style.cssText=["position:absolute;width:61px;height:20px;top:0;",
"left:"+(this.W-61)+"px;","margin:0;padding:0;margin-bottom:5px;cursor:pointer;overflow:hidden;"].join(""),f.innerHTML='<div style="width:40px;height:20px;background-color:#999999;color:#fff;float:left;margin-right:1px;font-size:12px;font-family:\u5fae\u8f6f\u96c5\u9ed1;text-align: center;line-height:20px;">\u5173\u95ed</div><a style="maring:0;padding:0;display:inline-block;border:none;overflow:hidden;height:20px;line-height:20px;cursor:pointer;width:20px;background:url(\'http://cpro.baidustatic.com/cpro/ui/noexpire/img/2.0.1/xuanfu_close.png\') no-repeat 0 0;margin-bottom:3px;float:left" ></a>',
c="position:absolute;left:0;top:25px;");b.appendChild(e);b.appendChild(f);f=document.createElement("div");c=["width:"+this.rb+"px;","height:"+this.qb+"px;","overflow:hidden;"+c];c.push("padding:4px;");c.push("border:#acacac 1px solid;");f.style.cssText=c.join("");this.L+="&adclass=1&conW="+this.rb+"&conH="+this.qb;f.innerHTML=d.ia('<div style="display:none">-</div><iframe id="{iframeId}" src="{cproServiceUrl}{paramString}" width="{iframeWidth}" height="{iframeHeight}" align="center,center" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" allowtransparency="true"></iframe></div>',
{iframeId:this.b,cproServiceUrl:this.T,paramString:this.L,iframeWidth:this.rb,iframeHeight:this.qb});b.appendChild(f);this.xa(b);for(var c=document.body.children,f=c.length,g=10>c.length?c.length:10,j=document.body.lastChild,i=0;i<g;i++){var k=c[f-i-1].getAttribute("data-baidu-dan-id");if(k||""===k){j=c[f-i-1];break}}j.parentNode.insertBefore(b,j);e.onclick=a.k(this.Vc,this);e.onmouseover=a.k(this.Xc,this);e.onmouseout=a.k(this.Wc,this)},sd:function(){var a=2;return a=1===this.qc?this.H?1===this.Ga?
4:3:1===this.Ga?2:1:1===this.Ga?6:5},rd:function(){var a=this.Ab;return a=0>a||9999<a?0:Math.floor(a)},td:function(){var a=this.Bb;return a=0>a||9999<a?this.Jc[this.J].ec:Math.floor(a)},od:function(){var a=this.vb;4095<a&&(a=4095);return a=Math.floor(a)},U:function(){this.Ma&&clearTimeout(this.Ma);this.Ma=setTimeout(a.k(this.de,this),50)},de:function(){var a=document.getElementById(this.R);a&&this.xa(a)},xa:function(a){a.style.position=this.H?(1===this.J||2===this.J)&&2===this.qc?"absolute":"fixed":
"absolute";var b=i.F(window),c=i.Ia(window),d=i.o(window),f=i.j(window),h=this.W,g=this.la+this.lc,j=this.Jc[this.J].fc,k=e.s(document.body,"position").toString(),z=e.s(document.body,"width").toString().replace("px",""),A=this.sd(),F="right",v,E,C=this.rd(),G=this.td();v=this.od();var Z=e.X(document.body).left;v=Math.floor((d-v)/2)-h-10;v=0<=v&&0==A%2?v:7;switch(A){case 1:case 2:"relative"===k&&"auto"!=z&&d>z?(h=d-v-h-Z,c=c+v-Z):(h=c+d-v-h,c+=v);F="left";E=Math.max(1===j?f>=g+G?b+G:b+f-g:f>=g+G?b+
f-G-g:b,C);break;case 3:case 4:c=h=v;1===j?E=Math.max(f>=g+G?G:f-g,C-b):(E=Math.min(b+f-C-g,G),E=Math.min(E,f-g));break;case 5:case 6:"relative"===k&&"auto"!=z&&d>z?(h=d-(d-z)/2-v-h,c=c+v-(d-z)/2):(h=c+d-v-h,c+=v);F="left";E=Math.max(1===j?G:f>=g+G?f-G-g:0,C);break;default:c=h=10}if(1===A%4||2===A%4)j=1;b=j?"top":"bottom";1===(this.sa&1)?(a=a.style,a.left=c+"px",a[b]=E+"px",a.visibility="visible"):2===(this.sa&2)&&(a=a.style,a[F]=h+"px",a[b]=E+"px",a.visibility="visible")},Vc:function(){var a=document.getElementById(this.R);
if(2===this.ub){var b="bd_close_"+this.g,c=g.ga(b,window),c=c?c|this.sa:this.sa;g.ya(b,c,{path:"/"})}a.parentNode&&a.parentNode.removeChild?a.parentNode.removeChild(a):document.body.removeChild(a);a={jk:this.gb||"",dt:(new Date).getTime(),rnd:Math.floor(2147483648*Math.random())};try{i.be(d.ia("http://eclick.baidu.com/fcb.jpg?jk={jk}&dt={dt}&rnd={rnd}",a),window)}catch(e){}},Xc:function(){var a=document.getElementById(this.b+"CloseBtn");a&&(1===this.J?a.style.backgroundColor="#0066cc":(a.getElementsByTagName("div")[0].style.backgroundColor=
"#0066cc",a.getElementsByTagName("a")[0].style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/2.0.0/xuanfu_mouseover_close.png)"))},Wc:function(){var a=document.getElementById(this.b+"CloseBtn");a&&(1===this.J?a.style.backgroundColor="#999999":(a.getElementsByTagName("div")[0].style.backgroundColor="#999999",a.getElementsByTagName("a")[0].style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/2.0.1/xuanfu_close.png)"))}})});return{render:function(d){var e;
if(i.G())e=u;else if(e=parseInt(d._html.ww||0,10),4095<e&&(e=4095),e>=screen.width)e=u;else{var f=e=u;e=/iphone|ipod|android|blackberry|opera mini|opera mobi|skyfire|maemo|windows phone|palm|iemobile|symbian|symbianos|fennec/i.test(navigator.userAgent.toLowerCase());f=/ipad|android 3|sch-i800|playbook|tablet|kindle|gt-p1000|sgh-t849|shw-m180s|a510|a511|a100|dell streak|silk|SAMSUNG.*Tablet|Galaxy.*Tab|SC-01C|GT-P1000|GT-P1003|GT-P1010|GT-P3105|GT-P6210|GT-P6800|GT-P6810|GT-P7100|GT-P7300|GT-P7310|GT-P7500|GT-P7510|SCH-I800|SCH-I815|SCH-I905|SGH-I957|SGH-I987|SGH-T849|SGH-T859|SGH-T869|SPH-P100|GT-P3100|GT-P3108|GT-P3110|GT-P5100|GT-P5110|GT-P6200|GT-P7320|GT-P7511|GT-N8000|GT-P8510|SGH-I497|SPH-P500|SGH-T779|SCH-I705|SCH-I915|GT-N8013|GT-P3113|GT-P5113|GT-P8110|GT-N8010|GT-N8005|GT-N8020|GT-P1013|GT-P6201|GT-P7501|GT-N5100|GT-N5110|SHV-E140K|SHV-E140L|SHV-E140S|SHV-E150S|SHV-E230K|SHV-E230L|SHV-E230S|SHW-M180K|SHW-M180L|SHW-M180S|SHW-M180W|SHW-M300W|SHW-M305W|SHW-M380K|SHW-M380S|SHW-M380W|SHW-M430W|SHW-M480K|SHW-M480S|SHW-M480W|SHW-M485W|SHW-M486W|SHW-M500W|GT-I9228|SCH-P739|SCH-I925|GT-I9200|GT-I9205|GT-P5200|GT-P5210|SM-T311|SM-T310|SM-T210|SM-T211|SM-P900|IdeaTab|S2110|S6000|K3011|A3000|A1000|A2107|A2109|A1107/i.test(navigator.userAgent.toLowerCase());
e=1024>screen.width&&e&&!f?u:m}if(e){if(d&&d._html){var k=d._html;e=parseInt(k.fa,10);var f=parseInt(k.ls,10),n=d.id.split("_")[0],r=0;2===parseInt(k.ct,10)&&(r=parseInt(g.ga("bd_close_"+n),10));k=[];1===e||2===e?(2===(f&2)&&2!==(r&2)&&k.push(b(d,"2002",2)),1===(f&1)&&1!==(r&1)&&k.push(b(d,"2001",1))):(f=3!==f?f:2,r!=f&&k.push(b(d,1===f?"2003":"2004",f)));d=k}else d=l;e=d.length;for(f=0;f<e;f++)if(r=d[f])k={I:r.I,z:r.z,aa:r.aa,R:r.b},c.Ta(k)&&((new j(r)).Vb(),c.ib(k),a(r))}}}});
V&&V("union/mobile","union/business/businessLogic,union/common/logic,union/common/bom,union/common/dom,union/common/cookie,union/DynamicFloatDecorator,union/preview".split(","),function(f,g,e,i,d,c,k){function b(a,b,c,f,g){function k(){"top"==c?x.style.top=o+"px":"bottom"==c&&(x.style.bottom=o+"px")}function r(a,b){var c=a,d=setInterval(function(){c--;0>=c&&(clearInterval(d),b&&b())},1E3)}var f=f||5,g=g||0.5,x=document.getElementById(a+"Wrap");x.style.display="block";var B=document.getElementById(a),
a=document.getElementById("xuantingCloseBtn_"+b),o=-1*(parseInt(x.style.height,10)+parseInt(a.style.height,10)),y=u,z=u,A=u;k();x.style.cssText+="-webkit-transition: all .3s linear;-moz-transition: all .3s linear;-ms-transition: all .3s linear;-o-transition: all .3s linear;transition: all .3s linear;";this.Qb=e.F();this.Oa=0;var F,v,E=Math.max(document.documentElement.clientHeight,window.innerHeight||0)*g,C=this;i.bind(a,"click",function(){k();A=m;d.ya("bd_close_"+b,1,{path:""})});i.bind(window,"scroll",
function(){F=e.F();v=F>C.Qb?"down":"top";C.Oa+=F-C.Qb;C.Qb=F;"top"===v&&!A&&Math.abs(C.Oa)>=E&&!z?("top"==c?x.style.top=0:x.style.bottom=0,y||(B.src=B.getAttribute("_src"),y=m),z=m,r(f,function(){k();z=u;C.Oa=0})):"down"===v&&(C.Oa=0)})}var a=window;return{Ob:function(a){this.g=a.id.split("_")[0];this.Ja=1;var b=a._html;this.b="cproIframe"+(b.dai||0);"u0"===this.g&&(this.Za=m);this.scale=b.scale||"20.3";this.i=parseInt(b.xuanting||0,10);"20.5"===this.scale&&(this.i=0);var c=this.scale.split(".");
this.K=this.vd(b.rsi0);this.D=Math.ceil(this.K/c[0]*c[1]);this.Ad(b.n);this.yb="BaiduCproExpansion"+this.b;this.gd=parseInt(a._html.expansion||0,10)},fb:function(a){var b=a._html||{},c=a.displayType,d=b.tn||"",e=d.toLowerCase(),f=b.ch||0,g=parseInt(b.stid||0,10),a=a.qn||"",i=b.n||"",B=b.dai||0;b.hasOwnProperty("stid")&&(b.stid=g);(g=b.skin)||(g="mobile_skin_white_red");var o=parseInt(b.at||99,10);4===(o&4)&&(b.at=o^4);this.i&&"mobile_skin_white_red"===g&&(g="mobile_skin_black_white");b.skin=g;b.rsi0=
this.K;b.rsi1=this.D;this.i&&(this.Sb(),o=12*this.K/640,b.conbw=0,b.conbl=o);if(e&&(-1<e.indexOf("tlink")||-1<e.indexOf("linkunit_1")))this.b+=(new Date).getTime().toString();if("07095078_1_cpr"===i||"07095078_cpr"===i||"71049059_cpr"===i||"68056018_cpr"===i)b.titSU="0";b.dtm="BAIDU_DUP2_SETJSONADSLOT";b.dc="2";b.di=this.g;b.wt=1;switch(this.i){case 0:b.distp="1001";break;case 2:b.distp="2005";break;case 3:b.distp="2006";break;case 4:b.distp="2007"}if(!b.adn||0===parseInt(b.adn||0,10))b.adn=1;this.Pb()&&
this.yb&&(b.expToken=this.yb);b.conW=this.K;b.conH=this.D;var o=[],y;for(y in b)y&&b.hasOwnProperty(y)&&o.push(""+y+"="+encodeURIComponent(b[y].toString()));y="http://pos.baidu.com/acom?";var o=o.join("&"),z=k.Gb(b,c);z&&z.serviceUrl!==l&&z.paramString!==l&&(y=z.serviceUrl,o=z.paramString);return{g:this.g,K:this.K,D:this.D,I:c,z:e,Aa:i,Sa:B,pa:f,La:a,aa:"unknown",T:y,L:o,A:parseInt(b.delayIn||0,10),B:parseInt(b.delayOut||0,10),w:b.sessionSync!==u&&"false"!==b.sessionSync,l:b.closeFor,i:this.i,Yb:d,
Oe:g,b:this.b}},Ad:function(b){if("19076084_1_cpr"===b){for(var c=/android/gi.test(navigator.userAgent),b=document.getElementsByTagName("meta"),d=0;d<b.length;d++)if("viewport"==b[d].name){var e=b[d].content;if(-1<e.indexOf("initial-scale")){this.Ja=e.match(/initial-scale=(\d(.\d)*)/)[1];break}}this.K/=this.Ja;this.D/=this.Ja;1!==this.Ja&&i.bind(a,"onorientationchange"in a?"orientationchange":"resize",function(){setTimeout(function(){i.c(this.b+"Wrap").style.width=a.innerWidth+"px"},c?1E3:0)})}},
vd:function(b){b=this.Za?b:Math.max(320,Math.min(a.innerWidth,a.innerHeight));isNaN(b)&&(b=Math.min(e.o(),e.j()));return b},Qd:function(b){var c=b.rss1||"#000",d="",d="opacity:"+parseFloat(b.opacity||0.9)+";",b="absolute";e.H()&&(b="fixed");this.i&&(d+="position:"+b+";");2===this.i?(this.Sb(),d+="top:0;background-color:"+c+";"):3===this.i&&("fixed"===b?d+="bottom:0;background-color:"+c+";":(b=e.F(a)+e.j(a)-this.D,d+="top:"+b+"px;background-color:"+c+";"));return d},Od:function(){if(!this.i)return"";
var a=this.Sb();return g.ia("<div id=\"xuantingCloseBtn_{slotId}\" style=\"position:absolute;right:0;top:{top}px;width:{closeBtnWidth}px;height:{closeBtnHeight}px;overflow:hidden;display:block;background:url('{closeBtnImgUrl}') no-repeat 0 0;_filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled=true, sizingMethod=none, src='{closeBtnImgUrl}');_background:none;cursor:pointer;background-position:center;background-size:100% 100%;z-index:2147483647;\">&nbsp;</div>",{slotId:this.g,right:""+
a.$c,top:"20.2"===this.scale?this.D:"-"+a.kc,closeBtnWidth:""+a.ad,closeBtnHeight:a.kc,closeBtnImgUrl:"http://cpro.baidustatic.com/cpro/ui/noexpire/img/2.0.0/xuantingClose"+a.Zc+".png"})},Pd:function(b){var c=this.Od(b),d=this.Qd(b),e="100%",b=b.n;1!=this.Ja&&"19076084_1_cpr"===b&&(e=a.innerWidth+"px");return['<div style="display:none">-</div>','<div id="{iframeId}Wrap" style="text-align:center;display:'+(0===this.i||1===this.i?"block":"none")+";font-size:0;width:"+e+";height:"+this.D+"px;"+d+'">',
'<div style="width:'+this.K+"px;height:"+this.D+'px;position:relative;margin:0 auto;">',c,'<iframe id="{iframeId}" '+(0===this.i||1===this.i?"src":"_src")+'="{serviceUrl}{paramString}" ','width="{iframeWidth}" height="{iframeHeight}" align="center,center" marginwidth="0"  marginheight="0" scrolling="no" frameborder="0" allowtransparency="true" style="margin-left:{iframMarginLeft}px" ></iframe><iframe src="http://cpro.baidustatic.com/cpro/ui/html/appDetect.html" width="0" height="0"align="center,center" marginwidth="0"  marginheight="0" scrolling="no" frameborder="0" allowtransparency="true" style="margin-left:{iframMarginLeft}px" ></iframe></div></div>'].join("")},
ge:function(){var b=document.createElement("div"),c=Math.min(e.o(),e.j()),d=Math.max(e.o(),e.j()),f=b.style;f.position="fixed";f.left="0";f.top=d+"px";f.zIndex=2147483647;f.background="#ffffff";f.width="100%";f.Re=f.WebkitTransition=f.MozTransition=f.te="top 1s ease-in-out";document.body.appendChild(b);var k=this.yb,n=this.b;i.bind(a,"message",function(d){i.c(n);if("object"===typeof d&&d.data&&(d=d.data,!(0>d.indexOf(k)))){d=d.slice(k.length);b.innerHTML=g.ia('<iframe id="{lpIframeId}" src="{clickUrl}" width="{iframeWidth}" height="{iframeHeight}" align="center,center" marginwidth="0"  marginheight="0" frameborder="0"></iframe><div id="{lpIframeId}_closeBtn" style="position:absolute;right:0;top:0;width:{closeBtnSize}px;height:{closeBtnSize}px;overflow:hidden;display:block;background:url(\'http://cpro.baidustatic.com/cpro/ui/noexpire/img/2.0.0/xuantingClose.png\') no-repeat 0 0; _filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled=true, sizingMethod=none, src=\'http://cpro.baidustatic.com/cpro/ui/noexpire/img/2.0.0/xuantingClose.png\');_background:none;cursor:pointer;background-position:center;background-size:100%,100%;">&nbsp;</div>',
{lpIframeId:n+"ExpansionLP",clickUrl:d,iframeWidth:e.o(),iframeHeight:e.j(),closeBtnSize:80*c/640});b.style.top="0";var f=i.c(n+"ExpansionLP"),p=function(){var a=e.o(),b=e.j();f.style.width=a+"px";f.style.height=b+"px";f.setAttribute("width",a);f.setAttribute("height",b)};i.bind(a,"resize",p);var o=i.c(n+"ExpansionLP_closeBtn");i.bind(o,"click",function(){b.style.top=Math.max(e.o(),e.j())+"px";b.innerHTML="";i.Mc(o,"click",arguments.callee);i.Mc(a,"resize",p)})}})},Sb:function(){var a=40,b="",b=2===
this.i?4:3,a=0.125*Math.max(document.documentElement.clientWidth,window.innerWidth||0);return{ad:a,kc:0.4*a,$c:16*(a/50),Zc:b}},Pb:function(){var b=!!/(iPhone|iPad|iPod|iOS)/i.test(a.navigator.userAgent),c="postMessage"in a,d=!b&&1===this.gd&&c;this.Pb=function(){return d};return d},render:function(e,h){e.displayType="inlay-mobile";var k="true"===e._html.cpro_enable_hidden_float?m:u,t=parseInt(e._html.cpro_close_time,10)||5,t=3<=t?t:3,s=parseInt(e._html.cpro_show_dist,10)||5,s=5<=s?s:5;if(k){if(this.Sc)return u;
this.Sc=m}var n=parseInt(e._isMlt||0,10);this.Ob(e);var r=this.fb(e),x=f.Kb(r.g,h),B={I:r.displayType,z:r.styleType,aa:r.stuffType,R:r.b};if(4===n&&!f.Ta(B))return u;var o=d.ga("bd_close_"+this.g,a);if(!(0!=r.l&&o)){var o=this.Pd(e._html,r),y={iframeId:r.b,serviceUrl:r.T,paramString:r.L,iframeWidth:r.K,iframeHeight:r.D,iframeMarginLeft:""};2==this.i||3==this.i&&document.body&&document.body.appendChild?(x=document.createElement("div"),x.innerHTML=g.ia(o,y),document.body.appendChild(x)):x?x.innerHTML=
g.ia(o,y):document.write(g.ia(o,y));this.Pb()&&this.ge();if(this.i){var z;2===this.i?z="top":3===this.i&&(z="bottom");k&&"u0"!=e.id?b(r.b,r.g,z,t,(1/s).toFixed(2)):c.me({r:r.b+"Wrap",ca:r.b,h:this.i,Ra:this.K,ka:this.D,re:"xuantingCloseBtn_"+r.g,De:r.La,g:r.g,l:r.l,Z:m,f:z,A:r.A,B:r.B,w:r.w,pe:"xuanting4CloseBtn_"+r.g});var A=document.createElement("div");A.id=this.b+"Wrap_placeholder";A.style.width="100%";A.style.height=this.D+"px";A.style.margin="0";A.style.padding="0";A.style.background="none";
A.style.border="none";2===this.i?document.body.insertBefore(A,document.body.firstChild):3===this.i&&i.bind(a,"load",function(){document.body.appendChild(A)})}4===n&&f.ib(B)}}}});})();